### ISSUE TITLE
Neptune Integration

### ISSUE THREAD

**Issue by jamesdolezal** [jamesdolezal/slideflow#117]
The `neptune` branch needs to be integrated into dev and tested.

The plan is to create a new branch off dev called `neptune_james`, manually review changes in the old `neptune` branch, and integrate. 

I will post comments/updates here as I review.

Commit changelog:

**Neptune Integration** (050c8ab)
-- added neptune.ai logging features
-- logs metadata for train & eval models (i.e. hps)
-- metrics uses psutil package to log GPU, CPU, memory, usage
-- tracks log output & error output
-- logs model summary, slide manifest
-- metrics log batch performance (loss, acc, val_loss, val_acc)
-- records results per epoch, logs results on graphs
-- now include AP, optimum threshold, cat. accuracy in results
-- uploads graphs feature (ROCs, AUPRCs, histograms)
-- tracks git commit info & code snippets

**Add Neptune flag; add give API, workspace option** (4170435)
- changed default option to use neptune to false
- added "-n" flag to give option to use neptune
- added SFP method to provide neptune workspace+API token in actions.py
- there may be better method of doing this

**Add neptune flag and import actions.py from path** (1f26274)
- flag (-n) as cmd line arg to store results to neptune (default false)
- run_project.py flag (-a)+give actions.py  path to import from anywhere

**Pushing second round of neptune changes** (60bd7b3)
- untested
- there have been a number of changes to dev
- pushing only to merge in dev changes again
- updated ROC/PRAUC curve plots to include outcome labels
- cleaned up some neptune metrics to log
- added additional stats to track (F1 score, prec, recall etc)
- added option to save plots or not
- added code to track heatmaps (didn't finish)

**Merge branch 'dev' into neptune** (9fdd899)
- kept all of my neptune updates
- incorporate new stats (F1, recall, precision)
- accepted all of dev logging updates
- accepted test suite dev changes
- made sure to keep preserved site code which was not in dev

**Neptune, TIFFs, statistics, plots, summarize** (0b68a79)
- Neptune integration fixes
- logs training HPs, eval model info, statistics, plots
- logs slide_manifest.log, tile_preds.csv
- TIFF format fixes to gen MPP from res, xdim
- vips2numpy alpha channel bug fix
- plots have more detailed titles
- option to save or not save plots
- added spec, sens, f1, kappa metrics
- changed format of results dict
- added new methods to summarize classes (work in progress)

**Comment by andrewsris** [comment]
I know that Neptune integration was the priority for the lab, but is it significantly harder to allow more general machine learning experiment tracking to be flexible and allow for integration of other platforms such as Weights and Biases or Comet.ml?

I assume it is in fact significantly harder, and other-platform integration should definitely be low priority, but just wanted to offer my thoughts. I tried to see if there is a high-level API that allows for multi-platform integration, but I am unable to find one.

**Comment by jamesdolezal** [comment]
W&B is pretty similar to Neptune all things considered, and I don't think really jived with comet when we tried it out before. But there are a ton of similar experiment tracking options out there:

- SACRED https://github.com/IDSIA/sacred
- Weights and Biases https://www.wandb.com/
- ML Flow https://mlflow.org/
- comet ml https://www.comet.ml/
- Neptune https://neptune.ai/
- Studio https://github.com/studioml/studio
- Datmo https://github.com/datmo/datmo
- Lore https://github.com/instacart/lore
- FORGE https://github.com/akosiorek/forge
- Sumatra https://pythonhosted.org/Sumatra/
- RandOpt https://github.com/seba-1511/randopt
- Pachyderm https://github.com/pachyderm/pachyderm
- feature Forge https://github.com/machinalis/featureforge 
- ModelChimph ttps://github.com/ModelChimp/modelchimp
- PolyAxonhttps://github.com/polyaxon/polyaxon
--Kubeflowhttps://github.com/kubeflow/kubeflow
-- Optuna https://optuna.readthedocs.io/en/stable/
-- Valohai https://valohai.com/


I'm not sure it's practical to implement more than what we are actively using, since there are so many possible choices out there, we'll never be able to support them all. With that being said, I am happy to consider the idea of supporting others if there is a reason to do so (integrating with  a framework another institution already uses and is familiar with)
