### ISSUE TITLE
[BUG] Inappropriate filtering when outcome variables contains value "FALSE" or "0"

### ISSUE THREAD

**Issue by andrewsris** [jamesdolezal/slideflow#134]
## Description
When the outcome categorical variable includes the values of "FALSE" or "0",  then slideflow only selects the the non-NA and non-"FALSE" and non-"0" categories. 

Because my outcome had TRUE/FALSE/NA, slideflow only extracted the TRUE outcomes, then trained and predicted TRUE with 100% accuracy. I changed the outcome to "1", "0", and "NA", or "1", "0" and [blank], but it did not fix it the issue. Once I changed the outcome to be "y", "n", and [blank], then slideflow was able to recognize the negative category and train appropriately. 

For example, then the outcome "jak2_present_binary" included outcomes of "1", "0", or [blank], then the following message occurs:
> 2021-12-20 13:24:51 [INFO] - jak2_present_binary '1.0' assigned to value '0' [25 slides]
> 2021-12-20 13:24:51 [INFO] - Training model jak2_present_binary-HP0 (k-fold iteration 1)...

But changing the outcome "jak2_present_binary" to "y", "n", or [blank], then the correct message appears:
> 2021-12-20 13:32:50 [INFO] - jak2_present_binary 'n' assigned to value '0' [5 slides]
> 2021-12-20 13:32:50 [INFO] - jak2_present_binary 'y' assigned to value '1' [25 slides]
> 2021-12-20 13:32:50 [INFO] - Training model jak2_present_binary-HP0 (k-fold iteration 1)...

**Comment by jamesdolezal** [comment]
This should be fixed in f745b5e, which will be included in the v1.0.5 update. Please comment or re-open the issue if still present with this fix.
