### ISSUE TITLE
Using slide-level predictions that differ within the same patient

### ISSUE THREAD

**Issue by andrewsris** [jamesdolezal/slideflow#135]
## Feature
I am using the run_project.py and actions.py workflow, which heavily relies on slideflow.Project objects. However, my current diagnostic task is to train a network to predict bone marrow fibrosis grade on a slide. Because multiple slides per patient may have different fibrosis scores at different times, there likely will be different outcomes per patient.

When trying to run the analysis, slideflow outputs an error when running training_validation_split because there are multiple outcome labels per patient.

It is not clear to me how to go about doing this type of analysis using slideflow.Project objects. I have tried changing the val_strategy to no avail. I know that the "trick" is to tell slideflow that each slide is actually a unique patient (which is not technically true, but it would fix the issue). 

## Pitch
I propose an additional flag in slideflow.Project.train() such as "outcome_uniqueness_group" that can clarify that the outcome is unique to the patient or unique to the slide (or potentially later on, unique to the tile).

## Alternatives
Otherwise the ability to reassign patient names in an already established sf.Project object would suffice. I would not recommend this approach as much, because the syntax would be confusing to the user. 

I know that there is documentation on how to reassign patient names to individual slides using the slideflow.model.Trainer() functions, but I am trying to stick with the slideflow.Project interface.

**Comment by jamesdolezal** [comment]
> I know that the "trick" is to tell slideflow that each slide is actually a unique patient (which is not technically true, but it would fix the issue).

This would be the preferred method of addressing your use case. The "patient" identifier is simply an ID column that enables support for multiple slide images per ID. If each slide has its own outcome, just duplicate the "slide" column and name it "patient".

While I think it's reasonable to consider add the option for an outcome to be slide-level or patient-level (perhaps argument `outcome_level='patient'` vs `outcome_level='slide'`), it would require a moderate amount of refactoring and could introduce new issues of its own. For simplicity, I would recommend the workaround described above. If this becomes burdensome or a recurring issue, we can explore a more definitive solution.

**Comment by siemdejong** [comment]
Hi! Is the method above currently the only way to approach this issue?

In my use case, we have multiple images of the same patient. The images can be very similar, but that is not always the case. Images can have their own label. I would like to avoid having image A and B (two images that are very similar) to be in the train and val set.

```
# annotations.csv
...
4,malignant,train,A.tiff
4,uncertain_malignant,train,B.tiff
...
```

```python
train_dataset, test_dataset = dataset.split(
    model_type='classification', # Categorical labels
    labels='category',            # Label to balance between datasets
    splits='splits.json',         # Where to save/load crossfold splits
    val_fraction=0.3,
    val_strategy="fixed",
)
```
throws a `DatasetSplitError: Multiple labels found for 4 (1, 4)`.

How would you approach this in slideflow?
