### ISSUE TITLE
[BUG] Error when resizing image during tile extraction it target size is too close to initial size

### ISSUE THREAD

**Issue by andrewsris** [jamesdolezal/slideflow#137]
## Description
I am getting an error when extracting a 40x magnification (micron=75). The slides have a mpp of 0.25. The initial extracted till is first 300pixels, and then gets resized by slideflow to 299 pixels. I believe this is too small of a re-sizing that results in an error from lipvips, similar to this issue: https://github.com/libvips/libvips/issues/1793

The error I obtain is:
>GLib-GObject-WARNING **: 09:45:56.731: value "0" of type 'gint' is invalid or out of range for property 'width' of type 'gint'
This error is displayed for each tile, which floods the console

This does not occur when I set micron = 302 or 151, but it will occur if I set micron = 75, 75.5, 76, or 100. 

## To Reproduce
>     P.extract_tiles(tile_px=299, **tile_um=75,**
>        filters={"source": ["Sinai2021"]},
>        skip_missing_roi=False,
>        grayspace_fraction=0.9,
>        qc='blur',
>        dry_run=True)

## Expected behavior
Expecting the tile extraction to be successful at higher effective magnification

## Additional context
Cannot share information publicly, so will reach out to you personally.

**Comment by jamesdolezal** [comment]
I was unable to reproduce this error when testing using slides from the publicly available TCGA dataset. Can you provide the following additional version information:

Libvips version:

**Comment by andrewsris** [comment]
Thanks James. I haven’t had a chance to confirm if this issue is still going on, but I assume it is. I am not sure how to check what version of libvips I have, but I looked in the libvips folder in the ChangeLog file, and the most recent log was for version 8.11.3 on 7/14/2021. I can try to update libvips, but I will have to try to remember how we manually did it, because I don’t have sudo priveliges on this machine. I think my libvips version is already past 8.9. Did you have an earlier version before? What version do you have now?

Thanks,
Andrew
