### ISSUE TITLE
Unable to generate training/val split; no tfrecords found

### ISSUE THREAD

**Issue by xiao-uofc** [jamesdolezal/slideflow#139]
## Description
    raise ValueError("Unable to generate training/val split; no tfrecords found")
ValueError: Unable to generate training/val split; no tfrecords found

## To Reproduce
1. Created dataset column containing "train" and "eval" values
2. run python3 run_project.py -p path command
3.

## Expected behavior

expecting training in progress, but failed
## Environment:

 - Slideflow Version (e.g., 1.0): 1.0.5
 - OS (e.g., Ubuntu): Ubuntu 18
 - How you installed PyTorch (`pip`, source):
 - Python version: 3.7
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by jamesdolezal** [comment]
Thanks for submitting a report! This message is displayed when TFrecords - the binary file format storing extrated tile image data - can't be found. The most likely cause is that you haven't run tile extraction, or that the TFRecord path is set incorrectly in your `datasets.json` file.

Have you extracted tiles from slides yet? If so, did you encounter any errors?

Can you confirm that the path to the tfrecords directory is correctly set in datasets.json, and that the *.tfrecords files exist?

Please also consider posting your project's `actions.py` file here.

**Comment by xiao-uofc** [comment]
Dear James,

Thanks for your reply. Before this run, the tile files as well as tfrecords have been extracted previously, so we are only doing training here. The tile/tfrecords paths are correctly provided in the data.json file. 

Here is the **actions.py**. The tile extraction code are commented out.

```
def main(P):
    # Perform tile extraction
    # -----------------------
    #P.extract_tiles(tile_px=299, tile_um=302)

    #Configure model parameters
    # --------------------------
    from slideflow.model import ModelParams
    hp = ModelParams(
    epochs=[1, 5],
    model='xception',
    loss='sparse_categorical_crossentropy',
    learning_rate=0.0001,
    batch_size=8)
    # Train a model
    # -------------
    P.train(
          'category',
          params=hp,
          filters = {
              'dataset': 'train',
              'category': ['negative', 'positive']
          }
     )

**Comment by jamesdolezal** [comment]
Thanks - can you post the full console output you get from the run_project.py script?

It may be an issue with the filters. What do you get when you run the following code in an interactive shell:

```
import slideflow as sf
```

**Comment by xiao-uofc** [comment]
Dear James,

Thank you for your guidance and sorry for the delayed responses.

I run the above and it indicates the project was not picking up any tile data nor tfrecords. 
I think the problem is the new annotation file does not talk to the old data path, so I tried a number of things but none of them worked, so I start regenerating the tiles and tfrecords.
I would like to understand how to let the annotations.csv talks to the fold data path eventually, but right now I think making the new tiles and tfrecords will help us move the project along a little faster.
I will keep you posted.

Best regards, Xiao

**Comment by xiao-uofc** [comment]
Using the newly generated tfrecords, the trainings is working now !!

**Comment by jamesdolezal** [comment]
Great! Glad to hear it.

**Comment by jamesdolezal** [comment]
You should be able to find additional information about where your projects look for the tfrecords data in [this article](https://slideflow.dev/project_setup.html), under "Configuring Datasets".

**Comment by xiao-uofc** [comment]
Really appreciate your help and guidance! The library works quite well :)
