### ISSUE TITLE
[BUG] generate_features_for_clam requesting params.json

### ISSUE THREAD

**Issue by OncologyDS** [jamesdolezal/slideflow#175]
## Description
When using the generate_features_for_clam module I get the following error: "slideflow.errors.ModelParamsNotFoundError: Model parameters file (params.json) not found", returned from line 675 of the __init__.py file in function get_model_config. This happens when I point either to a pre-saved file or pass the name of an architecture. 

As CLAM uses a pre-trained model, I suspect it should not be calling what seems to be a hyperparameter options file. Is this behaviour correct? And if so, how can a params.json be generated?

## To Reproduce
`
from __future__ import annotations
import slideflow as sf

project_init = sf.Project(
    '/path/to/project'
)

project_init.add_source(
    name = "D1_modeltest",
    slides='/path/to/slides',
    roi= "/path/to/roi",
    tiles='/path/to/tiles',
    tfrecords='/path/to/tfrecords'
)

dataset = project_init.dataset(tile_px=299, tile_um=302)

params = sf.ModelParams(
    tile_px=299,
    tile_um=302,
    batch_size=32
)

project_init.generate_features_for_clam(
    model='/path/to/resnet50.pt', #OR 'resnet50'
    outdir='/path/to/clamfeatures',
    layers=['postconv'],
    dataset=dataset
)
`

Sample error message:

in <module> project_init.generate_features_for_clam(
  File "/home/kxsz365/.conda/envs/slideflow_tf/lib/python3.10/site-packages/slideflow/project_utils.py", line 30, in _impl
    config = sf.util.get_model_config(model)
  File "/home/kxsz365/.conda/envs/slideflow_tf/lib/python3.10/site-packages/slideflow/util/__init__.py", line 675, in get_model_config
    raise errors.ModelParamsNotFoundError
slideflow.errors.ModelParamsNotFoundError: Model parameters file (params.json) not found.

## Expected behavior
I would expect the module to run without requesting such a file, as model is pre-trained

## Environment:

 - Slideflow Version (e.g., 1.0): 140148901c8881a30d46f64cac01eca6bd019c13
 - How you installed PyTorch (`pip`, source): pip
 - Python version: 3.10

## Additional context
Let me know if other information would be of use

**Comment by jamesdolezal** [comment]
When using a pretrained-only model (using ImageNet weights), specify the only the model name (e.g. `'resnet50'`), rather than a path to a saved model:

```python 
project_init.generate_features_for_clam(
  model='resnet50',
  outdir='/path/to/clamfeatures',
  layers=['postconv'],
  dataset=dataset
)
```

The functionality which enables this has not been released on PIP, so ensure that you are running from the latest master branch. It will eventually be released with version 1.2.0.

Additionally, if you want to use the `.generate_features_for_clam()` function to generate final layer activations from a saved model, that model must be a Slideflow-saved model (cannot be an arbitrary Tensorflow/Keras or Pytorch model). All Slideflow-saved models have a `params.json` file in the model directory.

**Comment by OncologyDS** [comment]
My bad, it appears that although I had gotten version 140148901c8881a30d46f64cac01eca6bd019c13 I was not directing the code to it. It now runs when using a model name. And thank you for clarifying things re. using a slideflow saved model.

**Comment by OncologyDS** [comment]
Hi - I have reopened this issue as I am getting the exact same error when specifying a model name other than resnet50. I have attempted to set:

`project_init.generate_features_for_clam(`
`  model='inception',`
`  outdir='/path/to/clamfeatures',`
`  layers=['postconv'],`
`  dataset=dataset`
`)`

Or

`project_init.generate_features_for_clam(`
`  model='vgg16',`
`  outdir='/path/to/clamfeatures',`
`  layers=['postconv'],`
`  dataset=dataset`
`)`

based on the models available in the ModelParams class in https://github.com/jamesdolezal/slideflow/blob/master/slideflow/model/tensorflow.py. Are these models not yet available in Slideflow?

**Comment by jamesdolezal** [comment]
Thanks for raising the issue. Inception and VGG16 are supported models. I can confirm that I'm able to run the code you linked above on the master branch (version 1.2.4) without raising any errors. Can you double check that you're running the correct slideflow version by printing the following:

```
import slideflow as sf
print(sf.__version__)
```

**Comment by OncologyDS** [comment]
I am closing this as my tests suggest this is clearly a local or VS code issue. Whether the environment works or not seems to depend on the path in the terminal, which is mind boggling to me but not an issue for you to figure out.
