### ISSUE TITLE
Tutorial on the inclusion of bespoke blur and artifact detection methods 

### ISSUE THREAD

**Issue by OncologyDS** [jamesdolezal/slideflow#180]
## Feature
It would be helpful for the Slideflow user to be able to include their own tile selection methods in the Slideflow pipeline. This would allow them to have more control over tile inclusion based upon their own needs. A tutorial explaining how to do this would be help enable users to tinker with the pre-processing pipeline.

## Pitch
If a tutorial could be added to the documentation explaining how to use or contribute to the existing code to include bespoke methods for tile selection it would help increase the versatility of Slideflow, enabling users to control what goes into their analysis on a finer level. Users could then contribute their methods to the Slideflow community after testing. This would enable the building of a machine learning in pathology community around shared tools.

## Additional context
The tile selection process can be key to the outcome of ML/DL processes, and so it is worth providing the user with a high level of control over this.

Thank you for considering this.

**Comment by jamesdolezal** [comment]
Thank you for this feature request and your patience. Version 1.3 includes a couple new tools to assist users in tinkering with the tile selection process, and I've [written a tutorial](https://slideflow.dev/tutorial6.html) on the use of bespoke filtering methods.

Tile-based filtering methods apply filtering criteria based on calculated grayspace (HSV colorspace) or whitespace. You can now use the interactive tool Workbench to [preview the effects](https://slideflow.dev/workbench_tools.html#preview-tile-filter) of tuning these grayspace/whitespace parameters in real-time.

Slide-based filtering methods filter tiles based on a boolean mask applied to the whole-slide image, and include Otsu's thresholding and blur detection. Workbench also includes tools for [previewing these slide filtering methods](https://slideflow.dev/workbench_tools.html#preview-slide-filter).

Also new in version 1.3, you can now apply an arbitrary boolean mask to a slide to perform custom filtering - this is described [in the new tutorial](https://slideflow.dev/tutorial6.html). Briefly, use the `WSI.apply_qc_mask()` function to apply a boolean mask for slide filtering:

```python
import slideflow as sf

wsi = sf.WSI('slide.svs', ...)
wsi.apply_qc_mask(boolean_mask)
```

Let me know what you think! Happy to expand the toolset to improve usability. Thank you again for the suggestion.

**Comment by OncologyDS** [comment]
Hi James,

Thank you for implementing this and giving further clarity and control over this process.  The workbench tool also looks like a really powerful and interesting addition to SlideFlow! 

I will have a go at implementing some of these features in my pipelines in the coming weeks and let you know how it goes.

**Comment by jamesdolezal** [comment]
Great, keep me posted on what you find. For now, I will close this issue.
