### ISSUE TITLE
[BUG] AttributeError: module 'slideflow' has no attribute 'clam'

### ISSUE THREAD

**Issue by OncologyDS** [jamesdolezal/slideflow#182]
## Description
When running CLAM through slideflow, I am getting the error "AttributeError: module 'slideflow' has no attribute 'clam' " when using `clam_args = sf.clam.get_args(k=1) `.

## To Reproduce
`# 0. Initialise a project`
`import slideflow as sf`

`P = sf.Project(...)`

`# 1. Specify directory locations`
`P.add_source(...)`

`# 2. Extract tiles`
`P.extract_tiles(...)`

`# 3. Define dataset`
`dataset = P.dataset(...)`

`# 4. Generate tile level features for CLAM`
`P.generate_features_for_clam(
      model='resnet50',
      outdir='/path/to/clamfeatures',
      layers=['postconv'],
      dataset=dataset
  )`

 `# 5. Decide on CLAM arguments`
`clam_args = sf.clam.get_args(k=1)`

The error message appears when running step 5.  

## Expected behavior
I would expect the  sf.clam.get_args(k=1) to attribute as expected. 

## Environment:
 - Slideflow Version: 1.2.3

## Additional context
Looking at the github I can see that the get_args exists at https://github.com/jamesdolezal/slideflow/blob/master/slideflow/clam/__init__.py. I am not sure why the attribute error arises. 

As a side note: the get_args function is not currently fully documented. I can see many more options in the code than those suggested in the tutorial. It would be helpful for these to be listed with the other functions, so that users know that they can tinker with these.

**Comment by jamesdolezal** [comment]
Thanks for raising the issue. The clam submodule needs to be explicitly imported, as it is not imported by default.

```
import slideflow as sf
import slideflow.clam

clam_args = sf.clam.get_args(k=1)
```

Thank you for your feedback on the documentation for the `get_args()` function. We initially did not write detailed documentation for this function as the arguments as those described in the original CLAM implementation, but we will expand this documentation to improve user experience.

**Comment by OncologyDS** [comment]
Thank you for the prompt response and clarifying this.

No worries, I can see that slideflow is in active development. I appreciate the work you have put into the package, it is overall quite very nice to work with to test various functions. Hope you have a good weekend.
