### ISSUE TITLE
[BUG] Annotations file: category fails if numeric

### ISSUE THREAD

**Issue by OncologyDS** [jamesdolezal/slideflow#183]
## Description
As part of the CLAM pipeline, using an annotations file where the category using numeric labelling causes a failure when using P.train_clam(). Specifically, my annotations file had category labels of either 0 or 1. Using these, slideflow returned the error that num_samples had to be a positive integer. Replacing 0 and 1 with Negative and Positive stopped this issue from occurring. 

## To Reproduce
1. Create an annotations file with patient, category, dataset and slide columns
2. Populate the category column with numeric values
3. Include in the CLAM pipeline as detailed in https://slideflow.dev/clam.html
4. Run CLAM, error will occur at P.train_clam()

Example below:

A. With numeric values:

label dictionary: {'0': 0, '1': 1}
number of classes: 2
slide-level counts:  
 Series([], Name: label, dtype: int64)
Patient-LVL; Number of samples registered in class 0: 0
Slide-LVL; Number of samples registered in class 0: 0
Patient-LVL; Number of samples registered in class 1: 0
Slide-LVL; Number of samples registered in class 1: 0

B. With strings

label dictionary: {'Negative': 0, 'Positive': 1}
number of classes: 2
slide-level counts:  
 0    225
1    167
Name: label, dtype: int64
Patient-LVL; Number of samples registered in class 0: 225
Slide-LVL; Number of samples registered in class 0: 225
Patient-LVL; Number of samples registered in class 1: 167
Slide-LVL; Number of samples registered in class 1: 167

## Expected behavior
I expected the category column to work with numeric or string data. 

## Environment:

 - Slideflow Version (e.g., 1.0): 1.2.3

## Additional context
Thanks for looking into this.

**Comment by jamesdolezal** [comment]
Thanks for raising the issue! It has now been fixed on the master branch and will be included in the next patch (1.2.5).

**Comment by OncologyDS** [comment]
Thanks for promptly looking into it. I am constantly impressed with the quick responses.
