### ISSUE TITLE
[BUG] Multiprocessing error when running on a batch schedule

### ISSUE THREAD

**Issue by andrewsris** [jamesdolezal/slideflow#186]
## Description
When running a non-interactive batched job, the slideflow workflow is interrupted during a multiprocessing step. I am attaching my actions.py script, my stdout file, and my stderr file. Note that this issue does NOT occur when running on an interactive job.

I believe this stackoverflow issue may be helpful:
https://stackoverflow.com/questions/13649625/multiprocessing-in-python-blocked

## To Reproduce
1. Run workflow through non-interactive batch job.

## Environment:

 - Slideflow Version (e.g., 1.0): 1.2.4
 - OS (e.g., Ubuntu): Ubuntu
 - How you installed PyTorch (`pip`, source): pip3
 - Python version: 3.8
 - CUDA/cuDNN version: 
 - GPU models and configuration: V100 x 4
 - Any other relevant information: 
[actions.txt](https://github.com/jamesdolezal/slideflow/files/9398737/actions.txt)
[stdout_70046320.txt](https://github.com/jamesdolezal/slideflow/files/9398738/stdout_70046320.txt)
[stderr_70046320.txt](https://github.com/jamesdolezal/slideflow/files/9398739/stderr_70046320.txt)

**Comment by jamesdolezal** [comment]
How did you submit the job? First guess is that multiprocessing freeze support might need to be enabled.

**Comment by andrewsris** [comment]
As it turns out, I think I was looking at the incorrect stdout and stderr.  I will do more digging, but presumably slideflow does in fact work with the batch scheduler.
