### ISSUE TITLE
[BUG] Bootstrap val_tfrecords & training_tfrecords AssertionError

### ISSUE THREAD

**Issue by skochanny** [jamesdolezal/slideflow#191]
## Description

Selecting 'bootstrap' as validation method during training results in assertion error.
![Screen Shot 2022-10-19 at 2 23 14 AM](https://user-images.githubusercontent.com/46627872/196623877-4d3e0b49-9cf8-4b73-b017-52f1b7091fd4.png)

REASON: val_tfrecords & training_tfrecords were not assigned

## Environment:
SF Version 1.3.0

## Solution --->
val_tfrecords and training_tfrecords were never assigned in the bootstrap validation step, just need to add following lines around dataset.py position 2574 in elif statement for val_strategy == 'bootstrap'

```
    # Return list of tfrecords
    val_tfrecords = [
        tfr for tfr in tfrecord_dir_list
        if path_to_name(tfr) in val_slides
    ]
    training_tfrecords = [
        tfr for tfr in tfrecord_dir_list
        if path_to_name(tfr) in train_slides
    ]
```

**Comment by jamesdolezal** [comment]
Thank you! Fixed in ea69f07
