### ISSUE TITLE
dataset.extract_tiles() doesn't work

### ISSUE THREAD

**Issue by Nazim0001** [jamesdolezal/slideflow#192]
Hi James,

Thank you for your reply. It is helpful.

I would like to see the extraction of tiles but I read this error after this "dataset.extract_tiles()":

LiveError                                 Traceback (most recent call last)
Input In [11], in <cell line: 1>()
----> 1 dataset.extract_tiles()

File ~/anaconda3/envs/slideflow/lib/python3.10/site-packages/slideflow/dataset.py:1186, in Dataset.extract_tiles(self, save_tiles, save_tfrecords, source, stride_div, enable_downsample, roi_method, skip_extracted, tma, randomize_origin, buffer, q_size, qc, report, **kwargs)
   1180 speed_task = pb.add_task("Speed: ",
   1181                          progress_type="speed",
   1182                          total=None)
   1183 slide_task = pb.add_task("Extracting...",
   1184                          progress_type="slide_progress",
   1185                          total=len(slide_list))
-> 1186 pb.start()
   1187 if buffer:
   1188     # Worker to put each slide path into queue
   1189     def buffer_worker():

File ~/anaconda3/envs/slideflow/lib/python3.10/site-packages/rich/progress.py:1160, in Progress.start(self)
   1158 """Start the progress display."""
   1159 if not self.disable:
-> 1160     self.live.start(refresh=True)

File ~/anaconda3/envs/slideflow/lib/python3.10/site-packages/rich/live.py:113, in Live.start(self, refresh)
    111 if self._started:
    112     return
--> 113 self.console.set_live(self)
    114 self._started = True
    115 if self._screen:

File ~/anaconda3/envs/slideflow/lib/python3.10/site-packages/rich/console.py:840, in Console.set_live(self, live)
    838 with self._lock:
    839     if self._live is not None:
--> 840         raise errors.LiveError("Only one live display may be active at once")
    841     self._live = live

LiveError: Only one live display may be active at once

Do you have any idea of this issue?

Thank you in advance for your assistance.
Best
Nazim

**Comment by jamesdolezal** [comment]
The `LiveError: Only one live display may be active at once` error is raised when there are multiple progress bars active. The most likely cause is that a progress bar is still active, maybe because the cell was previously aborted while running.

Try restarting the kernel, either by shutting down the notebook and resuming, or by clicking the "restart kernel" button in the notebook.

**Comment by Nazim0001** [comment]
Thank you James.

I thought that the issues comes from this:

>>> import slideflow as sf
Traceback (most recent call last):
  File
"/home/nazim/anaconda3/envs/slideflow/lib/python3.10/site-packages/pyvips/__init__.py",
line 19, in <module>
    import _libvips

*ImportError: libffi.so.7: cannot open shared object file: No such file or
directory*
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nazim/slideflow/slideflow/__init__.py", line 36, in <module>
    from slideflow import io, model, norm, stats
  File "/home/nazim/slideflow/slideflow/norm/__init__.py", line 79, in
<module>
    from slideflow.dataset import Dataset
  File "/home/nazim/slideflow/slideflow/dataset.py", line 113, in <module>
    from slideflow.slide import WSI, ExtractionReport, SlideReport
  File "/home/nazim/slideflow/slideflow/slide/__init__.py", line 43, in
<module>

*    import pyvips as vips*  File
"/home/nazim/anaconda3/envs/slideflow/lib/python3.10/site-packages/pyvips/__init__.py",
line 50, in <module>
    ffi = FFI()
  File
"/home/nazim/anaconda3/envs/slideflow/lib/python3.10/site-packages/cffi/api.py",
line 48, in __init__
    import _cffi_backend as backend

*ImportError: libffi.so.7: cannot open shared object file: No such file or
directory*


Do you know please how can I resolve it?


Thank you in advance

Best


*---*


*Nazim*

**Comment by jamesdolezal** [comment]
Ah, the error `*ImportError: libffi.so.7: cannot open shared object file: No such file or
directory*` indicates that it can't find libvips. You can verify this is the case by trying this code alone:

`import pyvips`

If that also raises the same error, then the problem is that libvips was not correctly installed.

How did you install libvips?

**Comment by Nazim0001** [comment]
Hi,
you're right libvips is not correctly installed because














*>>> import pyvipsTraceback (most recent call last):  File
"/home/nazim/anaconda3/envs/slideflow/lib/python3.10/site-packages/pyvips/__init__.py",
line 19, in <module>    import _libvipsImportError: libffi.so.7: cannot
open shared object file: No such file or directoryDuring handling of the
above exception, another exception occurred:Traceback (most recent call
last):  File "<stdin>", line 1, in <module>  File
"/home/nazim/anaconda3/envs/slideflow/lib/python3.10/site-packages/pyvips/__init__.py",
line 50, in <module>    ffi = FFI()  File
"/home/nazim/anaconda3/envs/slideflow/lib/python3.10/site-packages/cffi/api.py",
line 48, in __init__    import _cffi_backend as backendImportError:
libffi.so.7: cannot open shared object file: No such file or directory*

I installed it with this command:
conda install -c conda-forge libiconv

Apparently, it does not work. Do you know another one?
Thank you in advance
Best regards

*---*

*Nazim *

**Comment by Nazim0001** [comment]
HI James,
After installing several packages, import pyvips and slideflow are working now ;)  : 
   sudo apt-get update
   sudo apt-get upgrade
   sudo apt-get install -y libvips
   sudo apt-get install libffi7
Thank you for your help
Best 
Nazim

**Comment by Nazim0001** [comment]
Hi James,

Sorry, I am afraid to bother you again.

But, I can understand how you use the train part of your pipeline. I read a
lot of your tutorial about it and I miss something.
For example, for the training part about train_dts and val_dts, what I need
to be precise : the name of the dataset with filter...

   -

   train_dts (slideflow.Dataset
   <https://slideflow.dev/dataset.html#slideflow.Dataset>) – Training
   dataset. Will call the .tensorflow() method to retrieve the
   tf.data.Dataset used for model fitting.
   -

   val_dts (slideflow.Dataset
   <https://slideflow.dev/dataset.html#slideflow.Dataset>) – Validation
   dataset. Will call the .tensorflow() method to retrieve the
   tf.data.Dataset used for model fitting.

On the other hand, when I use the line following :

*P.train('RESPONDER', params='sweep.json',
filters={*'dataset'*[*'train'*],**,*'RESPONDER'*:* *[*'YES'*,*
'NO'*]**})*

It is not working. Maybe you have any idea of these issues ?

Best regards
Nazim

**Comment by Nazim0001** [comment]
Hi James,

Sorry to bother you. I had an issue and I don't why for my project I did
not extract WSIs. Any idea?
Thank you for your help.

best
Nazim

Here the error message:

P.extract_tiles(tile_px=100, # Tile size, in pixels.
tile_um="4x", #Tile size, in microns or magnification
save_tiles=True )

[00:52:16] INFO Filtering tiles by grayspace fraction

       INFO     Working on dataset source MyProject...

       INFO     Extracting tiles from 105 slides (tile_px=100,
tile_um=4x)

       INFO     Using 16 processes (pool=fork)

Speed: ?
Extracting... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0% 0/105 ● -:--:--
------------------------------

ImportError Traceback (most recent call last)
Cell In[10], line 3
1 # Extract tiles at 100 pixels, 4x
----> 3 P.extract_tiles(tile_px=100, # Tile size, in pixels.
4 tile_um="4x", #Tile size, in microns or magnification
5 save_tiles=True # save tile sur le disk
6 )

File
~/anaconda3/envs/tor_base/lib/python3.10/site-packages/slideflow/project.py:1677,
in Project.extract_tiles(self, tile_px, tile_um, filters, filter_blank,
**kwargs)
1550 """Extract tiles from slides.
1551
1552 Preferred use is calling :meth:slideflow.Dataset.extract_tiles.
(...)
1668
1669 """
1670 dataset = self.dataset(
1671 tile_px,
1672 tile_um,
(...)
1675 verification='slides'
1676 )
-> 1677 return dataset.extract_tiles(**kwargs)

File
~/anaconda3/envs/tor_base/lib/python3.10/site-packages/slideflow/dataset.py:1650,
in Dataset.extract_tiles(self, save_tiles, save_tfrecords, source,
stride_div, enable_downsample, roi_method, roi_filter_method,
skip_extracted, tma, randomize_origin, buffer, q_size, qc, report, **kwargs)
1648 else:
1649 for slide in slide_list:
-> 1650 wsi = _prepare_slide(
1651 slide,
1652 report_dir=tfrecord_dir,
1653 tma=tma,
1654 wsi_kwargs=wsi_kwargs,
1655 qc=qc,
1656 qc_kwargs=qc_kwargs)
1657 if wsi is None:
1658 pb.advance(slide_task)

File
~/anaconda3/envs/tor_base/lib/python3.10/site-packages/slideflow/dataset.py:149,
in _prepare_slide(path, report_dir, tma, wsi_kwargs, qc, qc_kwargs)
140 slide = sf.TMA(
141 path=path,
142 tile_px=wsi_kwargs['tile_px'],
(...)
146 report_dir=report_dir
147 ) # type: sf.slide._BaseLoader
148 else:
--> 149 slide = sf.WSI(path, **wsi_kwargs)
150 if qc:
151 slide.qc(method=qc, **qc_kwargs)

File ~/anaconda3/envs/tor_base/lib/python3.10/site-packages/slideflow/slide/
*init*.py:1012, in WSI.*init*(self, path, tile_px, tile_um, stride_div,
enable_downsample, roi_dir, rois, roi_method, roi_filter_method,
randomize_origin, pb, verbose, **kwargs)
943 def *init*(
944 self,
945 path: str,
(...)
957 **kwargs
958 ) -> None:
959 """Loads slide and ROI(s).
960
961 Args:
(...)
1010 missing, raises sf.errors.SlideMissingMPPError.
1011 """
-> 1012 super().*init*(
1013 path=path,
1014 tile_px=tile_px,
1015 tile_um=tile_um,
1016 stride_div=stride_div,
1017 enable_downsample=enable_downsample,
1018 pb=pb,
1019 **kwargs
1020 )
1022 # Initialize calculated variables
1023 self.extracted_x_size = 0 # type: int

File ~/anaconda3/envs/tor_base/lib/python3.10/site-packages/slideflow/slide/
*init*.py:260, in _BaseLoader.*init*(self, path, tile_px, tile_um,
stride_div, enable_downsample, pb, mpp, **reader_kwargs)
256 if self.filetype.lower() not in sf.util.SUPPORTED_FORMATS:
257 raise errors.SlideLoadError(
258 f"{self.name}: unsupported filetype '{self.filetype}'"
259 )
--> 260 if self.filetype.lower() not in backend_formats():
261 raise errors.IncompatibleBackendError(
262 f"{self.name}: filetype '{self.filetype}' is not supported "
263 f"by the current backend, {sf.slide_backend()}"
264 )
266 # Collect basic slide information

File
~/anaconda3/envs/tor_base/lib/python3.10/site-packages/slideflow/slide/backends/
*init*.py:30, in backend_formats()
28 return SUPPORTED_BACKEND_FORMATS
29 elif sf.slide_backend() == 'cucim':
---> 30 from .cucim import SUPPORTED_BACKEND_FORMATS
31 return SUPPORTED_BACKEND_FORMATS

File
~/anaconda3/envs/tor_base/lib/python3.10/site-packages/slideflow/slide/backends/cucim.py:12
10 from typing import Optional, Dict, Any, Tuple, List, TYPE_CHECKING
11 from slideflow.util import log
---> 12 from skimage.transform import resize
13 from skimage.util import img_as_float
14 from skimage.color import rgb2hsv

File
~/anaconda3/envs/tor_base/lib/python3.10/site-packages/skimage/transform/
*init*.py:4
1 from .hough_transform import (hough_line, hough_line_peaks,
2 probabilistic_hough_line, hough_circle,
3 hough_circle_peaks, hough_ellipse)
----> 4 from .radon_transform import (radon, iradon, iradon_sart,
5 order_angles_golden_ratio)
6 from .finite_radon_transform import frt2, ifrt2
7 from .integral import integral_image, integrate

File
~/anaconda3/envs/tor_base/lib/python3.10/site-packages/skimage/transform/radon_transform.py:5
3 from scipy.interpolate import interp1d
4 from scipy.constants import golden_ratio
----> 5 from scipy.fft import fft, ifft, fftfreq, fftshift
6 from ._warps import warp
7 from ._radon_transform import sart_projection_update

File ~/anaconda3/envs/tor_base/lib/python3.10/site-packages/scipy/fft/*init*
.py:91
89 from ._realtransforms import dct, idct, dst, idst, dctn, idctn, dstn,
idstn
90 from ._fftlog import fht, ifht, fhtoffset
---> 91 from ._helper import next_fast_len
92 from ._backend import (set_backend, skip_backend, set_global_backend,
93 register_backend)
94 from numpy.fft import fftfreq, rfftfreq, fftshift, ifftshift

File
~/anaconda3/envs/tor_base/lib/python3.10/site-packages/scipy/fft/_helper.py:3
1 from functools import update_wrapper, lru_cache
----> 3 from ._pocketfft import helper as _helper
6 def next_fast_len(target, real=False):
7 """Find the next fast size of input data to fft, for zero-padding, etc.
8
9 SciPy's FFT algorithms gain their speed by a recursive divide and conquer
(...)
59
60 """

File
~/anaconda3/envs/tor_base/lib/python3.10/site-packages/scipy/fft/_pocketfft/
*init*.py:3
1 """ FFT backend using pypocketfft """
----> 3 from .basic import *
4 from .realtransforms import *
5 from .helper import *

File
~/anaconda3/envs/tor_base/lib/python3.10/site-packages/scipy/fft/_pocketfft/basic.py:6
4 import numpy as np
5 import functools
----> 6 from . import pypocketfft as pfft
7 from .helper import (_asfarray, _init_nd_shape_and_axes, _datacopied,
8 _fix_shape, _fix_shape_1d, _normalization,
9 _workers)
11 def c2c(forward, x, n=None, axis=-1, norm=None, overwrite_x=False,
12 workers=None, *, plan=None):

ImportError:
/home/ben/anaconda3/envs/tor_base/lib/python3.10/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6:
version `GLIBCXX_3.4.30' not found (required by
/home/ben/anaconda3/envs/tor_base/lib/python3.10/site-packages/scipy/fft/_pocketfft/
pypocketfft.cpython-310-x86_64-linux-gnu.so)

!pip install fastai

import pandas as pd

#path = untar_data('
https://katherlab-datasets.s3.eu-central-1.amazonaws.com/tcga_crc_msih_subset_128.zip
')

#from google.colab import drive

#drive.mount('/content/drive', force_remount=True)

clini_df =
pd.read_csv('/home/ben/Documents/Gastric/clini_stad_chemo_response.csv') #
import clini csv for our TCGA-STAD data, the clini csv is a custom file

clini_df

*---*

*Nazim BENZERDJEB, MD, PhD *

PHU

Pathology Department

University Hospital of Lyon - South

165 Chemin du Grand Revoyet

69495 Pierre Bénite cedex

France
