### ISSUE TITLE
Version issue: scikit-learn >= 1.1 requires python>=3.8

### ISSUE THREAD

**Issue by lfbsdev** [jamesdolezal/slideflow#198]
## Description
Can't use slideflow>=1.3.0 on python 3.7 since scikit-learn >= 1.1 requires python>=3.8. Installation info states that slideflow works on python 3.7 .

## To Reproduce
1. Install python 3.7 .
2. Try installing slideflow using pip.

## Expected behavior

Sucessful installation of slideflow on python 3.7 .

## Environment:

 - Slideflow Version (e.g., 1.0): 1.3.0
 - OS (e.g., Ubuntu): Ubuntu
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.7
 - Any other relevant information: Kaggle environment (as of 2022/10/20)

## Additional context

Kaggle is a very popular environment for machine learning. It seems there currently is no way of updating python version on a Kaggle environment: [https://www.kaggle.com/questions-and-answers/210493](url). As such, I ask that slideflow be compatible to python 3.7 .

**Comment by jamesdolezal** [comment]
Thanks for opening this issue - we somewhat recently increased the version requirement of scikit-learn to >= 1.1, but I didn't realize that it causes an incompatibility with python 3.7. I'll work on a solution that retains python 3.7 compatibility and update here when it's finished.

**Comment by lfbsdev** [comment]
I appreciate that, thank you.

**Comment by jamesdolezal** [comment]
All tests have passed with scikit-learn == 1.0.2 on Python 3.7, so I've removed the >= 1.1 requirement. The scikit-learn >= 1.1 requirement was added during development of [1.3.0](https://github.com/jamesdolezal/slideflow/releases/tag/1.3.0), but final released version did not include features that requires 1.1. This change will be included in Slideflow 1.3.3, which should be released in the next week or so. 

With that said - I haven't included Kaggle environments in my testing approach yet, so there may be other issues you encounter. The big issue I imagine will be getting Libvips configured. I'll see if I can get a testing pipeline set up for Kaggle in the next month or so. Let me know if you encounter any other issues in the meantime.

**Comment by lfbsdev** [comment]
Alright. I had no problem with `libvips` using `apt`. I also installed `openslide-tools`, `python3-openslide` and `libcudnn8.`
Using pip I had to update `tensorflow-io` to 0.26.0 and install versioneer if building from source (perhaps these could be included in the requirements?).

The big difference in workflow is tile extraction. It seems libvips need write permission and kaggle input directory, which contains slides, is read-only. Because the working directory has write permissions but only 20GB, to extract slides, you must iterate through the slides copying one to the working directory, extracting tfrecords and deleting it. tfrecords themselves can also leave little space, so you may need to upload them to kaggle and use them in the input directory.

**Comment by jamesdolezal** [comment]
Slideflow has ways of avoiding TFRecords entirely (use the argument `P.train(..., from_wsi=True)` during training), but I'd like to do some additional testing to see if any other workaround are needed to get Kaggle environments working smoothly. I will open a separate issue and we can discuss there.
