### ISSUE TITLE
[BUG] SyntaxError: invalid sintax when using := operator on python 3.7 .

### ISSUE THREAD

**Issue by lfbsdev** [jamesdolezal/slideflow#207]
## Description

Slideflow 1.4.0 yields a SyntaxError at utils.
## To Reproduce
1. Install python 3.7
2. Install slideflow via pip
3. Import slideflow

```
File "/opt/conda/lib/python3.7/site-packages/slideflow/util/__init__.py", line 259
    while chunk := f.read(4096):
                 ^
SyntaxError: invalid syntax
```
## Expected behavior

Importing normally.
## Environment:

 - Slideflow Version (e.g., 1.0): 1.4.0
 - OS (e.g., Ubuntu): Ubuntu
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.7

## Additional context

The `:=` operator used was introduced in python 3.8 .

**Comment by jamesdolezal** [comment]
Whoops - thanks for catching. Fixed in 1a65eee and uploaded to pypi as 1.4.0.post1. Testing is now passing on Python 3.7, but let me know if there are any other issues you uncover.
