### ISSUE TITLE
[BUG] Setting max_tiles at tile generation makes no difference

### ISSUE THREAD

**Issue by lfbsdev** [jamesdolezal/slideflow#208]
## Description

Slideflow does not cap slide extraction through the `max_tiles` parameter passed at `slide.build_generator()`

## To Reproduce
1.

 ```
slide = sf.slide.WSI(filename, 224, 112)
slide.qc('both')
slide.build_generator(shuffle=True)
report = slide.extract_tiles(tfrecord_dir=dir)
print(f'slides extracted: {report.num_tiles}) #as a confirmation to info log
```

Yields `x` tiles.

2.

```
slide = sf.slide.WSI(filename, 224, 112)
slide.qc('both')
slide.build_generator(shuffle=True, max_tiles=300)
report = slide.extract_tiles(tfrecord_dir=dir)
print(f'slides extracted: {report.num_tiles}) #as a confirmation to info log
```
Yields `x` tiles.

## Expected behavior

Message `slides extracted: 300` .
## Environment:

 - Slideflow Version (e.g., 1.0): 1.4.0.post1
 - OS (e.g., Ubuntu): Ubuntu
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.7
 - Any other relevant information: Kaggle environment

**Comment by jamesdolezal** [comment]
`.build_generator()` is a low-level function which should not be directly called when extracting tiles with the `.extract_tiles()` interface - it is automatically, internally called by `.extract_tiles()` and all kwargs from `extract_tiles()` are passed to `build_generator()`. 

Instead of:

```python 
...
slide.build_generator(shuffle=True)
report = slide.extract_tiles(tfrecord_dir=dir)
```

try:

```python
...
report = slide.extract_tiles(tfrecord_dir=dir, max_tiles=300)
```

**Comment by lfbsdev** [comment]
Oh, I see. Thank you.
