### ISSUE TITLE
[BUG] AttributeError: module 'tensorflow.keras' has no attribute 'load_model' when resuming training.

### ISSUE THREAD

**Issue by lfbsdev** [jamesdolezal/slideflow#209]
## Description

Error raised when setting `resume_training` at `Project.Train()`
## To Reproduce
1.
`P.train(
    ...
    resume_training= path_to_model
)`

```
   1684             # Build model from ModelParams
   1685             if resume_training:
-> 1686                 self.model = tf.keras.load_model(resume_training)
   1687             else:
   1688                 model = self.hp.build_model(

AttributeError: module 'tensorflow.keras' has no attribute 'load_model'
```

## Expected behavior

Training resuming on model.
## Environment:

 - Slideflow Version (e.g., 1.0): 1.4.0.post1
 - OS (e.g., Ubuntu): Ubuntu
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.7
 - GPU models and configuration: T4x2
 - Any other relevant information: Tensorflow model.

## Additional context

Correct call would be `tf.keras.models.load_model()`

**Comment by jamesdolezal** [comment]
Thank you for raising this issue. I am surprised that this made it through - I thought for sure I had included transfer learning in our automatic testing. I will provide a fix and make sure the testing coverage includes this functionality for the future.

**Comment by jamesdolezal** [comment]
Fix has been merged with master, along with expansion of the automatic testing to include resuming from training, for both Tensorflow & PyTorch backends. Thank you again.
