### ISSUE TITLE
[BUG] cuCIM backend does not detect MPP on Philips TIFF slide

### ISSUE THREAD

**Issue by andrewsris** [jamesdolezal/slideflow#213]
## Description
When trying to do tile extraction on a TIFF slide scanned by an Philips scanner, cuCIM fails to detect the MPP and thus tile extraction cannot be performed. This problem does not exist when using the libvips backend. See attached error log. I can provide the slide in question if helpful.

## Script
    P.extract_tiles(tile_px=299, tile_um=302,
                    buffer='/ssd',
                    filters={"patient": ["RS-21-10522"]},
                    roi_method="auto",
                    qc='both',
                    dry_run=False)

## Environment:
 - Slideflow Version (e.g., 1.0): 1.4
 - OS (e.g., Ubuntu): Centos
 - How you installed Slideflow (`pip`, source): Docker
 - Python version: 3.8
 - CUDA/cuDNN version: 11.2
 - GPU models and configuration: A100
 - 
[cucim_error.txt](https://github.com/jamesdolezal/slideflow/files/10403227/cucim_error.txt)

**Comment by jamesdolezal** [comment]
Think I've fixed the issue - let me know if you encounter any other issues when using Philips slides.
