### ISSUE TITLE
Export qupath rois containing holes

### ISSUE THREAD

**Issue by juanenofbit** [jamesdolezal/slideflow#216]
Hi,

I have noticed that the QuPath script (qupath_roi.groovy ) that writes the CSV file used to define the ROI, does not properly process ROIs with holes. I am afraid that only simple polygons can be used.

As in the following example, with an tumor area where small parts are removed by the pathologyst for some reason:

![roi_in_qupath](https://user-images.githubusercontent.com/86926226/213402983-55e4c1d4-6e36-4573-ad37-469425dada6e.png)

This is a screenshot of the report, showing the extracted tiles (the area in black color) that does not correspond to the one marked in QuPath

![roi_in_report](https://user-images.githubusercontent.com/86926226/213403254-35f4d59d-c332-4ccf-9a9a-2ec71d85e67d.png)

**Comment by jamesdolezal** [comment]
Thanks for raising this issue! We hadn't encountered this use case before, but I can see its utility. I've added automatic hole detection for ROIs in d3125d3. You won't need to re-run the QuPath Groovy script, it will work on the existing CSV files.

It's available on `master` now and I'll plan to include it in 1.4.2.
