### ISSUE TITLE
Conditional statement potential error

### ISSUE THREAD

**Issue by matte-esse** [jamesdolezal/slideflow#217]
https://github.com/jamesdolezal/slideflow/blob/0826f403595ed9ca06cdf5d7868d545ac56ae581/slideflow/project.py#L3043

I think this line should be 
```
epochs = [e for e in ep_res if 'epoch' in e]
```

I suppose the intent is to have `'epoch'` match the substring of a string not an element in a list. If I'm correct the string being checked should be `e` not `ep_res.keys()`

**Comment by jamesdolezal** [comment]
Thanks! You're right. Thanks for catching.
