### ISSUE TITLE
Issue with model evaluation in clam

### ISSUE THREAD

**Issue by sreens** [jamesdolezal/slideflow#220]
I am getting the following error when trying to evaluate a clam model trained for a multi-class classification (3 classes):

.conda/envs/slideflow/lib/python3.10/site-packages/slideflow/clam/utils/eval_utils.py", line 107, in summary
if args.micro_average:
AttributeError: 'types.SimpleNamespace' object has no attribute 'micro_average'

Slideflow version used is 1.4.0.post1.

Please advise.

**Comment by jamesdolezal** [comment]
Thanks for raising this issue, the bug has been found and fixed in `master`. I will include the fix in the next release (1.4.2), which should be available soon.

**Comment by sreens** [comment]
Sorry, @jamesdolezal, I just noticed your reply. Thank you for your prompt action and response!
