### ISSUE TITLE
Load XML files and convert to CSV

### ISSUE THREAD

**Issue by emmachancellor** [jamesdolezal/slideflow#230]
https://github.com/jamesdolezal/slideflow/blob/aa99a45aaac9371208f65ce0a24428045d559871/slideflow/dataset.py#L2343-L2352

I want to write a helper function that converts XML files to CSV such that rois() will appropriately select the new CSV files. The point of this addition is to enable XML ROIs to be directly loadable into slideflow. This is relevant because images annotated in ImageScope end up with XML ROIs, and there are some slide scanners that scan images that will only open in ImageScope and not QuPath meaning that the ROIs can only be saved in XML format. I will create a PR with proposed changes soon.

**Comment by jamesdolezal** [comment]
Great suggestion. I would recommend working off the 'dev' branch, as I included some utility functions related to ROIs that would be helpful. For example, it includes functions to load ROIs from numpy arrays. If you write an XML parser that loads into numpy, you could load those arrays with the existing functions.

**Comment by jamesdolezal** [comment]
Implemented in #231.
