### ISSUE TITLE
Rules for extracting tiles from ROIs (centroids, full intersection,...)

### ISSUE THREAD

**Issue by juanenofbit** [jamesdolezal/slideflow#239]
How exactly are the extracted tiles selected from the ROIs?

I wonder if you use the criterion of the centroid of the tile falling within the ROI, or if you can choose a more scrict rule, forcing the whole tile to be within the ROI to create it.  I can't find it in the documentation.

The latter option would be preferable in my case, so I don't include non-annotated tissue in the training.

Thanks,
Juan.

**Comment by jamesdolezal** [comment]
Hi Juan,

Thanks for the question and suggestion. You are indeed correct that tiles are filtered through ROIs by centroid. However, in response to your suggestion, in aa7b781 I've added a new argument `roi_filter_method` that provides more granular control. 

`roi_filter_method` can either be "center" or a float (0-1). 
- If "center", tiles are filtered with ROIs based on the center of the tile, which is the current behavior.
- If a float (0-1), tiles are filtered based on the proportion of the tile inside the ROI, and ``roi_filter_method`` is interpreted as a threshold. If the proportion of a tile inside the ROI is greater than this number, the tile is included. For example, if `roi_filter_method=0.7`, a tile that is 80% inside of an ROI will be included, but a tile that is 50% in the ROI will be excluded.

With this behavior, you could achieve what you're looking for by setting `roi_filter_method=1`.

As an example, this is a slide extracted using "center":

![slide_thresh_center](https://user-images.githubusercontent.com/48372806/228725059-124cb98b-0a63-4599-99ec-f5f96abbc797.jpg)

This is with `roi_filter_method=1`:

![slide_thresh1](https://user-images.githubusercontent.com/48372806/228725085-2a502d1c-8368-4758-8343-85c50f15d995.jpg)

And this is `roi_filter_method=0.01`:

![slide_thresh01](https://user-images.githubusercontent.com/48372806/228725119-9e4cbde5-3ca6-4894-b0ec-218c3341a511.jpg)

Thanks again for the question and suggestion. This will be included in version 1.6.0 and the documentation will be updated accordingly.
