### ISSUE TITLE
[BUG] Placeholder title

### ISSUE THREAD

**Issue by billnjcn111** [jamesdolezal/slideflow#242]
This appears in using clam:
P.generate_features_for_clam(
    model='xception',
    outdir='./clam/',
    layers='postconv',
    dataset = dataset
)

AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_2039/3996529435.py in <module>
----> 1 P.generate_features_for_clam(
      2     #model='./external.models//UCH.RS/cp.ckpt.data-00000-of-00001',
      3     model='xception',
      4     outdir='./clam/',
      5     layers='postconv',

/opt/conda/lib/python3.8/site-packages/slideflow/project.py in generate_features_for_clam(self, model, outdir, dataset, layers, force_regenerate, min_tiles)
   1946 
   1947         # Set up activations interface
-> 1948         df = sf.DatasetFeatures(
   1949             model=model,
   1950             dataset=dataset,

/opt/conda/lib/python3.8/site-packages/slideflow/model/__init__.py in __init__(self, model, dataset, labels, cache, annotations, **kwargs)
    331         # Otherwise will need to generate new activations from a given model
    332         else:
--> 333             self._generate_from_model(model, cache=cache, **kwargs)
    334 
    335         # Now delete slides not included in our filtered TFRecord list

/opt/conda/lib/python3.8/site-packages/slideflow/model/__init__.py in _generate_from_model(self, model, layers, include_preds, include_uncertainty, batch_size, cache, **kwargs)
    444             combined_model = sf.model.Features.from_model(model, **feat_kw)
    445         elif is_torch:
--> 446             combined_model = sf.model.Features.from_model(
    447                 model,
    448                 tile_px=self.tile_px,

AttributeError: 'Features' object has no attribute 'to'
​
​

**Comment by jamesdolezal** [comment]
Thank you for raising this issue! I've fixed the problem in 07d62b8. I'll include this in a 1.5.4 patch release in the next day or two.
