### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.keras' with tensorflow as backend

### ISSUE THREAD

**Issue by Meijian** [jamesdolezal/slideflow#244]
## Description

I have been using slideflow with tensorflow as backend for weeks and it has been doing fine. But starting a couple of days ago, when I import slideflow, it gives me "No module named 'tensorflow.keras'" error. The torch backend works fine so far. Any thoughts?

## To Reproduce
Steps to reproduce the behavior in a notebook:

%env SF_BACKEND=tensorflow
%env SF_SLIDE_BACKEND=cucim
import slideflow as sf

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
File <command-2060504343245749>:1
----> 1 import slideflow as sf

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/__init__.py:26
     23 from slideflow.util import getLoggingLevel, log, setLoggingLevel, about
     25 ...
---> 26 from slideflow import io, model, norm, stats
     27 from slideflow.dataset import Dataset
     28 from slideflow.heatmap import Heatmap

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/model/__init__.py:24
     21 # --- Backend-specific imports ------------------------------------------------
     23 if sf.backend() == 'tensorflow':
---> 24     from slideflow.model.tensorflow import (CPHTrainer, Features, load, # noqa F401
     25                                             LinearTrainer, ModelParams,
     26                                             Trainer, UncertaintyInterface)
     27 elif sf.backend() == 'torch':
     28     from slideflow.model.torch import (CPHTrainer, Features, load, # noqa F401
     29                                        LinearTrainer, ModelParams,
     30                                        Trainer, UncertaintyInterface)

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/model/tensorflow.py:20
     16 from types import SimpleNamespace
     17 from typing import (
     18     TYPE_CHECKING, Any, Dict, List, Optional, Tuple, Union, Callable
     19 )
---> 20 from tensorflow.keras import applications as kapps
     22 import slideflow as sf
     23 import slideflow.model.base as _base

File /databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py:171, in _create_import_patch.<locals>.import_patch(name, globals, locals, fromlist, level)
    166 thread_local._nest_level += 1
    168 try:
    169     # Import the desired module. If you’re seeing this while debugging a failed import,
    170     # look at preceding stack frames for relevant error information.
--> 171     original_result = python_builtin_import(name, globals, locals, fromlist, level)
    173     is_root_import = thread_local._nest_level == 1
    174     # `level` represents the number of leading dots in a relative import statement.
    175     # If it's zero, then this is an absolute import.

ModuleNotFoundError: No module named 'tensorflow.keras'

1

## Environment:

 - Slideflow Version (e.g., 1.0):
 - OS (e.g., Ubuntu): Ubuntu 20.04.5 LTS
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.9
 - CUDA/cuDNN version: 8500
 - GPU models and configuration: Tesla T4
 - Any other relevant information: torch version: 1.13.0+cu117; tensorflow version: 2.10.0

**Comment by jamesdolezal** [comment]
Thanks for raising this issue. This sounds like an environmental problem or issue with Tensorflow installation. Can you run the following in a terminal and see if it also raises an error:

```python -c "import tensorflow.keras"```

If so, there is a problem with the Tensorflow installation and you could consider trying to reinstall tensorflow.

Also - what version of Tensorflow are you using?

**Comment by jamesdolezal** [comment]
I'm not able to reproduce this in Colab ([link](https://colab.research.google.com/drive/1CzwFms812ojHdl8K96hj52LZheKaLo_m?usp=sharing)).

The last line of the error output, which references the file `/databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/init.py`, makes me believe this is an issue with the databricks configuration.

Are you able to import tensorflow.keras in the notebook? What happens if you do:

```
%env SF_BACKEND=tensorflow
%env SF_SLIDE_BACKEND=cucim
from tensorflow.keras import applications as kapps
import slideflow as sf
```

**Comment by Meijian** [comment]
Thanks for confirming! The command produces the errors too: ModuleNotFoundError: No module named 'tensorflow.keras'

I think you are right, it's likely due to my Databricks configuration. Let me go back to check with our data engineering team. I will close the issue for now.
