### ISSUE TITLE
OSError: [Errno 95] Operation not supported when using DatasetFeatures

### ISSUE THREAD

**Issue by Meijian** [jamesdolezal/slideflow#245]
## Description

Hi James, first of all, congrats on the release of 2.0. It's exciting to see the new additions.
Here is an issue I encountered, not sure if it's a bug or my platform problem. 
I was using DatasetFeatures() function with pretrained resnet50 as model. The model seemed working initially with progress bar moving smoothly, but in the end, it gave an error message: OSError: [Errno 95] Operation not supported. I'd really appreciate if you have any suggestions!

## To Reproduce
1. %env SF_BACKEND=torch
%env SF_SLIDE_BACKEND=cucim

2. import slideflow as sf

3. from slideflow.model import build_feature_extractor
resnet50 = build_feature_extractor(
    'resnet50_imagenet',
    tile_px=299
)

4. P = sf.load_project(rootpath)
dataset=P.dataset(tile_px=299, tile_um='10x')

5. features = sf.DatasetFeatures(resnet50, dataset)

Detailed message:
fp.close()
OSError: [Errno 95] Operation not supported
Exception ignored in: <function ZipFile.__del__ at 0x7f4363c84f70>
Traceback (most recent call last):
  File "/usr/lib/python3.10/zipfile.py", line 1819, in __del__
    self.close()
  File "/usr/lib/python3.10/zipfile.py", line 1841, in close
    self._fpclose(fp)
  File "/usr/lib/python3.10/zipfile.py", line 1941, in _fpclose
    fp.close()
OSError: [Errno 95] Operation not supported
Exception ignored in:   File "/usr/lib/python3.10/zipfile.py", line 1819, in __del__
<function ZipFile.__del__ at 0x7f4363c84f70>
Traceback (most recent call last):
Exception ignored in:     self.close()
  File "/usr/lib/python3.10/zipfile.py", line 1841, in close
    <function ZipFile.__del__ at 0x7f4363c84f70>self._fpclose(fp)

Traceback (most recent call last):
  File "/usr/lib/python3.10/zipfile.py", line 1941, in _fpclose
  File "/usr/lib/python3.10/zipfile.py", line 1819, in __del__
        self.close()
  File "/usr/lib/python3.10/zipfile.py", line 1841, in close
fp.close()    self._fpclose(fp)

OSError  File "/usr/lib/python3.10/zipfile.py", line 1941, in _fpclose
    : fp.close()
OSError[Errno 95] Operation not supported: [Errno 95] Operation not supported

Exception ignored in: <function ZipFile.__del__ at 0x7f4363c84f70>
Traceback (most recent call last):
  File "/usr/lib/python3.10/zipfile.py", line 1819, in __del__
    self.close()
  File "/usr/lib/python3.10/zipfile.py", line 1841, in close
    self._fpclose(fp)Exception ignored in: 
  File "/usr/lib/python3.10/zipfile.py", line 1941, in _fpclose
<function ZipFile.__del__ at 0x7f4363c84f70>    
fp.close()Traceback (most recent call last):

  File "/usr/lib/python3.10/zipfile.py", line 1819, in __del__
OSError:     self.close()[Errno 95] Operation not supported
  File "/usr/lib/python3.10/zipfile.py", line 1841, in close

    self._fpclose(fp)
  File "/usr/lib/python3.10/zipfile.py", line 1941, in _fpclose
    fp.close()
OSError: [Errno 95] Operation not supported

---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/dataset.py", line 270, in _create_index
    tfrecord2idx.create_index(tfrecord, index_name)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/util/tfrecord2idx.py", line 58, in create_index
    np.savez(index_file, np.array(out_array))
  File "<__array_function__ internals>", line 5, in savez
  File "/databricks/python/lib/python3.10/site-packages/numpy/lib/npyio.py", line 618, in savez
    _savez(file, args, kwds, False)
  File "/databricks/python/lib/python3.10/site-packages/numpy/lib/npyio.py", line 721, in _savez
    with zipf.open(fname, 'w', force_zip64=True) as fid:
  File "/usr/lib/python3.10/zipfile.py", line 1180, in close
    self._fileobj.seek(self._zipfile.start_dir)
OSError: [Errno 95] Operation not supported
"""

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
File <command-3885990385620945>:2
      1 # Calculate features for this dataset.
----> 2 features = sf.DatasetFeatures(resnet50, dataset)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/features.py:146, in DatasetFeatures.__init__(self, model, dataset, labels, cache, annotations, **kwargs)
    144 # Otherwise will need to generate new activations from a given model
    145 elif model is not None:
--> 146     self._generate_features(cache=cache, **kwargs)
    148 # Now delete slides not included in our filtered TFRecord list
    149 loaded_slides = list(self.activations.keys())

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/features.py:323, in DatasetFeatures._generate_features(self, cache, **kwargs)
    320 # Calculate final layer activations for each tfrecord
    321 fla_start_time = time.time()
--> 323 activations, predictions, locations, uncertainty = fg.generate()
    325 self.activations = {s: np.stack(v) for s, v in activations.items()}
    326 self.predictions = {s: np.stack(v) for s, v in predictions.items()}

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/features.py:1358, in _FeatureGenerator.generate(self)
   1355 def generate(self):
   1356 
   1357     # Get the dataloader for iterating through tfrecords
-> 1358     dataset = self.build_dataset()
   1360     # Rename tfrecord_array to tfrecords
   1361     log.info(f'Calculating activations for {len(self.dataset.tfrecords())} '
   1362              f'tfrecords (layers={self.layers})')

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/model/features.py:1344, in _FeatureGenerator.build_dataset(self)
   1339     n_workers = (4 if self.tfrecords_have_loc else 1)
   1340     log.debug(
   1341         "Setting up PyTorch dataset iterator (num_workers="
   1342         f"{n_workers}, chunk_size=8)"
   1343     )
-> 1344     return self.dataset.torch(
   1345         None,
   1346         num_workers=n_workers,
   1347         chunk_size=8,
   1348         **self.dts_kw  # type: ignore
   1349     )
   1351 # Unrecognized feature generator.
   1352 else:
   1353     raise ValueError(f"Unrecognized model type: {type(self.model)}")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/dataset.py:3591, in Dataset.torch(self, labels, batch_size, rebuild_index, from_wsi, **kwargs)
   3589     clip = None
   3590 else:
-> 3591     self.build_index(rebuild_index)
   3592     tfrecords = self.tfrecords()
   3593     if not tfrecords:

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/slideflow/dataset.py:921, in Dataset.build_index(self, force)
    916 pool = mp.Pool(
    917     os.cpu_count(),
    918     initializer=sf.util.set_ignore_sigint
    919 )
    920 index_fn = partial(_create_index, force=force)
--> 921 for _ in track(pool.imap_unordered(index_fn, self.tfrecords()),
    922                description='Creating index files...',
    923                total=len(self.tfrecords()),
    924                transient=True):
    925     pass
    926 pool.close()

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/rich/progress.py:168, in track(sequence, description, total, auto_refresh, console, transient, get_time, refresh_per_second, style, complete_style, finished_style, pulse_style, update_period, disable, show_speed)
    157 progress = Progress(
    158     *columns,
    159     auto_refresh=auto_refresh,
   (...)
    164     disable=disable,
    165 )
    167 with progress:
--> 168     yield from progress.track(
    169         sequence, total=total, description=description, update_period=update_period
    170     )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/rich/progress.py:1210, in Progress.track(self, sequence, total, task_id, description, update_period)
   1208 if self.live.auto_refresh:
   1209     with _TrackThread(self, task_id, update_period) as track_thread:
-> 1210         for value in sequence:
   1211             yield value
   1212             track_thread.completed += 1

File /usr/lib/python3.10/multiprocessing/pool.py:873, in IMapIterator.next(self, timeout)
    871 if success:
    872     return value
--> 873 raise value

OSError: [Errno 95] Operation not supported

## Expected behavior

Expect features loaded to the features variable.

## Environment:

 - Slideflow Version (e.g., 1.0): 2.0
 - OS (e.g., Ubuntu): Ubuntu
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.9/3.10 (tried both)
 - CUDA/cuDNN version: 11.4 
 - GPU models and configuration: Tesla T4
 - Any other relevant information: Running in Databricks

**Comment by jamesdolezal** [comment]
It looks like this is a limitation with using dbfs file storage in databricks, which does not allow writing *.zip files:

https://stackoverflow.com/questions/70358327/how-can-we-perform-zip-operation-in-databricks-using-python-or-anyway

https://stackoverflow.com/questions/59713184/how-to-zip-files-on-azure-blob-storage-with-shutil-in-databricks

Slideflow uses TFRecord "index" files to record which bytes in a TFRecord are the starting location for new records. Index files are numpy arrays saved in [NPZ format](https://numpy.org/doc/stable/reference/generated/numpy.savez.html). These files are automatically generated when needed - and the DatasetFeatures interface is one example where these index files are needed.

The error is being raised because the DatasetFeatures interface triggered creation of the index files, but encountered an error because ZIP files cannot be created on dbfs file storage.

I think there are two possible solutions:
1) The index files are zipped to save storage space (using the `numpy.savez` function), but we could alternatively use `numpy.save`, which saves the files in *.npy format. Although this would solve the immediate issue, you're likely to encounter other problems, as this isn't the only function in Slideflow that saves *.zip files to disk (PyTorch models, as one example, are saved as *.zip files). It would also require some work and testing to ensure that the workflow remains cross-compatible with the existing *.zip index files.
2) If it is possible with your workflow/environment, you could consider switching your data storage to something that is compatible with ZIP files, and then transfer the files after they've been created.

If your data storage is flexible, I would recommend trying (2) first, and if it's not possible, I can start working on prototypes for (1)

**Comment by Meijian** [comment]
Hi James, thanks for looking into it. You are absolutely right about the limitations of writing zip files in databricks. I will contact our engineering team to see if it's easy to switch the root storage to something like s3 bucket. Even it's possible, it might take some time. For option 1, is it possible to fix it by catching the exception and write *.npy files if writing *.zip files failed? 

I know it's too much to ask but do you have a quick patch for me to get feature generation going in the meantime? My final outputs will be directed to s3 buckets, so PyTorch should be able to save the models. Thanks a lot!

**Comment by jamesdolezal** [comment]
Yes, this should be possible. I'll work on putting together a patch update.

Are you able to run from source? It would be helpful to confirm that the patch is successful before I roll it into master.

**Comment by Meijian** [comment]
Hi James, thanks for your help. Yes, I'm able to run from the source and the example code worked fine in my environment. I'm looking forward to the solution!

**Comment by jamesdolezal** [comment]
I've pushed an update to the branch `npy_index`. Let me know if that solves the error you were encountering. If so, I will roll into master and include in a 2.0.1 patch update.

**Comment by jamesdolezal** [comment]
Hmm... looks like the error handling I added isn't catching the OSError. I've added a temporary debugging workaround update on the `npy_index` branch that forces it to save with *.npy instead of *.npz. Can you refresh your git repository on this branch and see if it works? 

Apologies for this iterative process - this would be smoother if I had access to a similar environment.

**Comment by Meijian** [comment]
Just updated, no more error messages! Nice work!
I will see if the rest of the steps can go through, thank you again, James!

No need to apologize, I'm just happy that somebody can solve my problems. I will probably have more requests coming your way. :)

**Comment by jamesdolezal** [comment]
Sounds good. I'll work on a more permanent solution that we can integrate into the main branch. Let me know if anything else comes up - will close this for now.

**Comment by Meijian** [comment]
Awesome! Thank you, James. I will try this new version today. I will let you know if there is anything else.

**Comment by Meijian** [comment]
Hi James, you were right, the quick patch didn't fix all the issues related zip file. Now I'm facing a similar issue when save the features with to_torch() function. Could you please take a look at this one when you get a chance? Should I open a feature request to better support databricks platform? Thanks a ton!

OSError: [Errno 95] Operation not supported
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
File <command-3885990385620931>:2
      1 features = sf.DatasetFeatures(ctranspath, dataset=dataset)
----> 2 features.to_torch(rootpath + '/ctranspath/bag_directory/')

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/model/features.py:555, in DatasetFeatures.to_torch(self, outdir, slides)
    551     slide_activations = torch.from_numpy(
    552         self.activations[slide].astype(np.float32)
    553     )
    554     torch.save(slide_activations, join(outdir, f'{slide}.pt'))
--> 555     np.savez(join(outdir, f'{slide}.index'), self.locations[slide])
    556 args = {
    557     'model': self.model if isinstance(self.model, str) else '<NA>',
    558     'num_features': self.num_features
    559 }
    560 sf.util.write_json(args, join(outdir, 'settings.json'))

File <__array_function__ internals>:5, in savez(*args, **kwargs)

File /databricks/python/lib/python3.9/site-packages/numpy/lib/npyio.py:618, in savez(file, *args, **kwds)
    538 @array_function_dispatch(_savez_dispatcher)
    539 def savez(file, *args, **kwds):
    540     """Save several arrays into a single file in uncompressed ``.npz`` format.
    541 
    542     Provide arrays as keyword arguments to store them under the
   (...)
    616 
    617     """
--> 618     _savez(file, args, kwds, False)

File /databricks/python/lib/python3.9/site-packages/numpy/lib/npyio.py:722, in _savez(file, args, kwds, compress, allow_pickle, pickle_kwargs)
    720     # always force zip64, gh-10776
    721     with zipf.open(fname, 'w', force_zip64=True) as fid:
--> 722         format.write_array(fid, val,
    723                            allow_pickle=allow_pickle,
    724                            pickle_kwargs=pickle_kwargs)
    726 zipf.close()

File /usr/lib/python3.9/zipfile.py:1170, in _ZipWriteFile.close(self)
   1168     self._fileobj.seek(self._zinfo.header_offset)
   1169     self._fileobj.write(self._zinfo.FileHeader(self._zip64))
-> 1170     self._fileobj.seek(self._zipfile.start_dir)
   1172 # Successfully written: Add file to our caches
   1173 self._zipfile.filelist.append(self._zinfo)

OSError: [Errno 95] Operation not supported
