### ISSUE TITLE
Error training, slideflow.norm has no attribute torch

### ISSUE THREAD

**Issue by hardwayh** [jamesdolezal/slideflow#246]
## Description
Great new release!  I've been trying out the new features but having an issue in training a model, I get an error message "AttributeError: module 'slideflow.norm' has no attribute 'torch'".  I'm not sure if it is a bug or a change in how the dataset should be loaded in the new version.  I created the "sample_proj" from the previous release.

## To Reproduce

import slideflow as sf
P = sf.load_project(sample_proj)

dataset = P.dataset(tile_px=256,tile_um=128,
                    filters={'dataset': ['train','val']})

train_dataset = dataset.filter({"dataset": ["train"]})
val_dataset = dataset.filter({"dataset": ["val"]})

hp = sf.ModelParams(
    tile_px=256,
    tile_um=128,
    model='xception',
    batch_size=32,
    epochs=[3])

results = P.train(
  outcomes="outcome",
  params=hp,
  dataset=train_dataset,
  val_dataset=val_dataset
)

Error:
AttributeError                            Traceback (most recent call last)
Cell In[33], line 16
      7 val_dataset = dataset.filter({"dataset": ["val"]})
      9 hp = sf.ModelParams(
     10     tile_px=256,
     11     tile_um=128,
     12     model='xception',
     13     batch_size=32,
     14     epochs=[3])
---> 16 results = P.train(
     17   outcomes="outcome",
     18   params=hp,
     19   dataset=train_dataset,
     20   val_dataset=val_dataset
     21 )

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/project.py:3378, in Project.train(self, outcomes, params, dataset, exp_label, filters, filter_blank, input_header, min_tiles, max_tiles, splits, mixed_precision, allow_tf32, load_method, balance_headers, process_isolate, **training_kwargs)
   3376     if exp_label:
   3377         hp_name = f'{exp_label}-{hp_name}'
-> 3378     self._train_hp(
   3379         hp_name=hp_name,
   3380         hp=hp,
   3381         outcomes=outcomes,
   3382         val_settings=val_settings,
   3383         ctx=ctx,
   3384         dataset=dataset,
   3385         filters=filters,
   3386         filter_blank=filter_blank,
   3387         input_header=input_header,
   3388         min_tiles=min_tiles,
   3389         max_tiles=max_tiles,
   3390         mixed_precision=mixed_precision,
   3391         allow_tf32=allow_tf32,
   3392         splits=splits,
   3393         balance_headers=balance_headers,
   3394         training_kwargs=training_kwargs,
   3395         results_dict=results_dict,
   3396         load_method=load_method,
   3397         process_isolate=process_isolate
   3398     )
   3399 # Print summary of all models
   3400 log.info('Training complete; validation accuracies:')

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/project.py:709, in Project._train_hp(self, hp_name, hp, outcomes, val_settings, ctx, dataset, filters, filter_blank, input_header, min_tiles, max_tiles, mixed_precision, allow_tf32, splits, results_dict, training_kwargs, balance_headers, process_isolate, **kwargs)
    707 for k in valid_k:
    708     s_args.k = k
--> 709     self._train_split(dataset, hp, val_settings, s_args)
    711 # --- Record results --------------------------------------------------
    712 if (not val_settings.source
    713     and (val_settings.strategy is None
    714          or val_settings.strategy == 'none')):

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/project.py:933, in Project._train_split(self, dataset, hp, val_settings, s_args)
    931     process.join()
    932 else:
--> 933     project_utils._train_worker(
    934         (train_dts, val_dts),
    935         model_kwargs,
    936         s_args.training_kwargs,
    937         s_args.results_dict,
    938         self.verbosity
    939     )

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/project_utils.py:147, in _train_worker(datasets, model_kw, training_kw, results_dict, verbosity)
    145 train_dts, val_dts = datasets
    146 trainer = sf.model.build_trainer(**model_kw)
--> 147 results = trainer.train(train_dts, val_dts, **training_kw)
    148 results_dict.update({model_kw['name']: results})

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/model/torch.py:1780, in Trainer.train(self, train_dts, val_dts, log_frequency, validate_on_batch, validation_batch_size, validation_steps, starting_epoch, ema_observations, ema_smoothing, use_tensorboard, steps_per_epoch_override, save_predictions, save_model, resume_training, pretrain, checkpoint, multi_gpu, norm_fit, reduce_method, seed, from_wsi, roi_method)
   1777 self.model = self.model.to(self.device)
   1779 # Setup dataloaders
-> 1780 self._setup_dataloaders(
   1781     train_dts=train_dts,
   1782     val_dts=val_dts,
   1783     mid_train_val=True,
   1784     roi_method=roi_method,
   1785     from_wsi=from_wsi,
   1786     pool=pool)
   1788 # Model parameters and optimizer
   1789 self._prepare_optimizers_and_loss()

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/model/torch.py:1216, in Trainer._setup_dataloaders(self, train_dts, val_dts, mid_train_val, incl_labels, from_wsi, **kwargs)
   1202 interleave_args = types.SimpleNamespace(
   1203     rank=0,
   1204     num_replicas=1,
   (...)
   1213     **kwargs
   1214 )
   1215 # Use GPU stain normalization for PyTorch normalizers, if supported
-> 1216 if self._has_gpu_normalizer():
   1217     log.info("Using GPU for stain normalization")
   1218     interleave_args.standardize = False

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/model/torch.py:853, in Trainer._has_gpu_normalizer(self)
    852 def _has_gpu_normalizer(self) -> bool:
--> 853     return (isinstance(self.normalizer, sf.norm.torch.TorchStainNormalizer)
    854             and self.normalizer.device != "cpu")

AttributeError: module 'slideflow.norm' has no attribute 'torch'

## Expected behavior
Completed training run.

## Environment:
%env SF_BACKEND=torch
%env SF_SLIDE_BACKEND=cucim

 - Slideflow Version (e.g., 1.0): 2.0
 - OS (e.g., Ubuntu): CentOS Linux 7
 - How you installed Slideflow: source
 - Python version: Python 3.9.13
 - CUDA/cuDNN version:11.0
 - GPU models and configuration:Tesla T4
Thanks!

**Comment by jamesdolezal** [comment]
This has been fixed in #c3fd541 and included in the 2.0.1 release.

**Comment by hardwayh** [comment]
Awesome, thanks so much for the quick fix!  Excited to use!

From: James Dolezal ***@***.***>
Date: Tuesday, April 11, 2023 at 4:50 PM
To: jamesdolezal/slideflow ***@***.***>
Cc: Hardway, Heather D., Ph.D. ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [jamesdolezal/slideflow] Error training, slideflow.norm has no attribute torch (Issue #246)

Whoops! I've tracked down the error here and will put out a patch update later today. In the meantime, the workaround would be to add the following at the top of your script:

import slideflow.norm.torch

**Comment by hardwayh** [comment]
Sorry, one more question – I successfully trained a model, but in evaluations I get a keyerror.  Again, I’m not sure if this is a but or an issue on my end, thanks!


# Method 1: specifying filters
P.evaluate(
  model=model,
  outcomes="outcome",
  filters={"dataset": ["test"]}
)

KeyError                                  Traceback (most recent call last)
Cell In[58], line 4
      1 model = "/infodev1/infoderm/Projects/Heather/slideflow_ex3/models/Trainer_epoch3.zip"
      3 # Method 1: specifying filters
----> 4 P.evaluate(
      5   model=model,
      6   outcomes="outcome",
      7   filters={"dataset": ["test"]}
      8 )

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/project_utils.py:32, in auto_dataset.<locals>._impl(obj, model, *args, **kwargs)
     30 @wraps(method)
     31 def _impl(obj, model=None, *args, **kwargs):
---> 32     return _filters_to_dataset(obj, method, model, *args, **kwargs)

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/project_utils.py:84, in _filters_to_dataset(obj, method, model, *args, **kwargs)
     77     raise errors.ProjectError("Missing argument 'model'.")
     78 dataset = obj.dataset(
     79     tile_px=config['hp']['tile_px'],
     80     tile_um=config['hp']['tile_um'],
     81     **{k: v for k, v in kwargs.items() if k in filter_keys},
     82     verification='slides'
     83 )
---> 84 return method(obj, model, *args, dataset=dataset, **kwargs)

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/project.py:1232, in Project.evaluate(self, model, outcomes, dataset, filters, filter_blank, min_tiles, checkpoint, eval_k_fold, splits, max_tiles, mixed_precision, allow_tf32, input_header, load_method, custom_objects, **kwargs)
   1176 """Evaluate a saved model on a given set of tfrecords.
   1177
   1178 Args:
   (...)
   1229
   1230 """
   1231 log.info(f'Evaluating model at [green]{model}')
-> 1232 trainer, eval_dts = self._prepare_trainer(
   1233     model=model,
   1234     dataset=dataset,
   1235     outcomes=outcomes,
   1236     checkpoint=checkpoint,
   1237     eval_k_fold=eval_k_fold,
   1238     splits=splits,
   1239     max_tiles=max_tiles,
   1240     input_header=input_header,
   1241     mixed_precision=mixed_precision,
   1242     allow_tf32=allow_tf32,
   1243     load_method=load_method,
   1244     custom_objects=custom_objects,
   1245 )
   1247 # Load the model
   1248 if isinstance(model, str):

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/project.py:443, in Project._prepare_trainer(self, model, dataset, outcomes, checkpoint, eval_k_fold, splits, max_tiles, mixed_precision, allow_tf32, input_header, load_method, custom_objects)
    441 if not predicting:
    442     dataset = dataset.filter(filter_blank=filter_blank)
--> 443     eval_dts, labels, unique = self._setup_labels(
    444         dataset, hp, outcomes, config, splits, eval_k_fold=eval_k_fold
    445     )
    446 else:
    447     eval_dts = dataset

File /infodev1/non-phi-projects/m251791/anaconda/anaconda3/envs/slideflow2/lib/python3.9/site-packages/slideflow/project.py:308, in Project._setup_labels(self, dataset, hp, outcomes, config, splits, eval_k_fold)
    306 """Prepare dataset and labels."""
    307 # Assign labels into int
--> 308 conf_labels = config['outcome_labels']
    309 if hp.model_type() == 'categorical':
    310     if len(outcomes) == 1 and outcomes[0] not in conf_labels:

KeyError: 'outcome_labels'


And checking the model configuration I get:

sf.util.get_model_config(model)

{'slideflow_version': '2.0.0+10.g6e22edd.dirty',
'hp': {'augment': 'xyrj',
  'batch_size': 32,
  'drop_images': False,
  'dropout': 0,
  'early_stop': False,
  'early_stop_method': 'loss',
  'early_stop_patience': 0,
  'epochs': [1],
  'hidden_layer_width': 500,
  'hidden_layers': 0,
  'include_top': True,
  'l1': 0.0,
  'l1_dense': 0.0,
  'l2': 0.0,
  'l2_dense': 0.0,
  'learning_rate': 0.0001,
  'learning_rate_decay': 0,
  'learning_rate_decay_steps': 100000,
  'loss': 'CrossEntropy',
  'manual_early_stop_batch': None,
  'manual_early_stop_epoch': None,
  'model': 'xception',
  'normalizer': None,
  'normalizer_source': None,
  'optimizer': 'Adam',
  'pooling': 'max',
  'tile_px': 256,
  'tile_um': 128,
  'toplayer_epochs': 0,
  'trainable_layers': 0,
  'training_balance': 'category',
  'uq': False,
  'validation_balance': 'none'},
'backend': 'torch'}


From: Hardway, Heather D., Ph.D. ***@***.***>
Date: Wednesday, April 12, 2023 at 9:44 AM
To: jamesdolezal/slideflow ***@***.***>
Subject: Re: [EXTERNAL] Re: [jamesdolezal/slideflow] Error training, slideflow.norm has no attribute torch (Issue #246)
Awesome, thanks so much for the quick fix!  Excited to use!

From: James Dolezal ***@***.***>
Date: Tuesday, April 11, 2023 at 4:50 PM
To: jamesdolezal/slideflow ***@***.***>
Cc: Hardway, Heather D., Ph.D. ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [jamesdolezal/slideflow] Error training, slideflow.norm has no attribute torch (Issue #246)

Whoops! I've tracked down the error here and will put out a patch update later today. In the meantime, the workaround would be to add the following at the top of your script:

import slideflow.norm.torch

**Comment by jamesdolezal** [comment]
Hmm, this is odd. How did you train the model? Did you use the `Project.train()` interface, or did you manually use a [`slideflow.model.Trainer`](https://slideflow.dev/training/#using-a-trainer)? 

I'm guessing you trained the model using the latter approach. If you train a model with `Project.train()`, it will automatically log the outcome labels in that `params.json` file, so you shouldn't get this error. If you trained a model using the [`slideflow.model.Trainer`](https://slideflow.dev/training/#using-a-trainer) approach, the outcome labels won't get logged in the `params.json` configuration file, since you're manually providing slide-level labels instead of providing the name of an outcome column. 

If you did use `slideflow.model.Trainer`, the process for model evaluation is a bit different. Looking through the documentation, I don't think I've clarified this point - I will work on updating the documentation accordingly.

**Comment by hardwayh** [comment]
I used a trainer, so trainer.train() – so that makes sense why I wasn’t able to evaluate it the same.  Thanks for the clarification!



From: James Dolezal ***@***.***>
Date: Wednesday, April 12, 2023 at 12:17 PM
To: jamesdolezal/slideflow ***@***.***>
Cc: Hardway, Heather D., Ph.D. ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [jamesdolezal/slideflow] Error training, slideflow.norm has no attribute torch (Issue #246)

Hmm, this is odd. How did you train the model? Did you use the Project.train() interface, or did you manually use a slideflow.model.Trainer<https://slideflow.dev/training/#using-a-trainer>?

I'm guessing you trained the model using the latter approach. If you train a model with Project.train(), it will automatically log the outcome labels in that params.json file, so you shouldn't get this error. If you trained a model using the slideflow.model.Trainer<https://slideflow.dev/training/#using-a-trainer> approach, the outcome labels won't get logged in the params.json configuration file, since you're manually providing slide-level labels instead of providing the name of an outcome column.

If you did use slideflow.model.Trainer, the process for model evaluation is a bit different. Looking through the documentation, I don't think I've clarified this point - I will work on updating the documentation accordingly.
