### ISSUE TITLE
[BUG] ValueError: This DataLoader does not contain any batches

### ISSUE THREAD

**Issue by dakomura** [jamesdolezal/slideflow#248]
## Description
Hi, 
I encountered the following error while performing MIL using the PyTorch backend with our original dataset. I'd appreciate your assistance in resolving this issue.  The weakly supervised, tile-based model was successfully trained on the same dataset.

## To Reproduce
import slideflow as sf
import slideflow.norm.torch

from slideflow.mil import mil_config
from slideflow.model import build_feature_extractor

P = sf.load_project('/project_dir')

dataset = P.dataset(tile_px=299, tile_um=302)

# Extract tiles from all slides in the dataset.
dataset.extract_tiles(qc='otsu', skip_extracted=True)

resnet50 = build_feature_extractor(
    'resnet50_imagenet',
    tile_px=299
)

# Calculate features for this dataset.
features = sf.DatasetFeatures(resnet50, dataset)

features.to_torch('/bag_dir')

train_dataset = dataset.filter({"dataset": ["train"]})
val_dataset = dataset.filter({"dataset": ["eval"]})

config = mil_config('attention_mil', lr=1e-3)

P.train_mil(
    config=config,
    outcomes='category',
    train_dataset=train_dataset,
    val_dataset=val_dataset,
    bags='/bag_dir',
    attention_heatmaps=True,
    cmap='magma',
    interpolation=None

)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[46], line 1
----> 1 P.train_mil(
      2     config=config,
      3     outcomes='category',
      4     train_dataset=train_dataset,
      5     val_dataset=val_dataset,
      6     bags='/bag_dir',
      7     attention_heatmaps=True,
      8     cmap='magma',
      9     interpolation=None
     10 
     11 )

File ~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project.py:3735, in Project.train_mil(self, config, train_dataset, val_dataset, outcomes, bags, exp_label, **kwargs)
   3701 r"""Train a multi-instance learning model.
   3702 
   3703 Args:
   (...)
   3731 
   3732 """
   3733 from .mil import train_mil
-> 3735 return train_mil(
   3736     config,
   3737     train_dataset,
   3738     val_dataset,
   3739     outcomes,
   3740     bags,
   3741     outdir=join(self.root, 'mil'),
   3742     exp_label=exp_label,
   3743     **kwargs
   3744 )

File ~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/mil/train/__init__.py:92, in train_mil(config, train_dataset, val_dataset, outcomes, bags, outdir, exp_label, **kwargs)
     89 outdir = sf.util.create_new_model_dir(outdir, exp_label)
     90 sf.util.write_json(config.json_dump(), join(outdir, 'mil_params.json'))
---> 92 return train_fn(
     93     config,
     94     train_dataset,
     95     val_dataset,
     96     outcomes,
     97     bags,
     98     outdir=outdir,
     99     **kwargs
    100 )

File ~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/mil/train/__init__.py:379, in train_fastai(config, train_dataset, val_dataset, outcomes, bags, outdir, attention_heatmaps, **heatmap_kwargs)
    376     all_bags = np.array(bags)
    378 # Build learner.
--> 379 learner = build_fastai_learner(
    380     config,
    381     train_dataset,
    382     val_dataset,
    383     outcomes,
    384     bags=all_bags,
    385     outdir=outdir,
    386 )
    388 # Train.
    389 _fastai.train(learner, config)

File ~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/mil/train/__init__.py:309, in build_fastai_learner(config, train_dataset, val_dataset, outcomes, bags, outdir)
    305 val_idx = np.array([i for i, bag in enumerate(bags)
    306                         if path_to_name(bag) in val_slides])
    308 # Build FastAI Learner
--> 309 learner = _fastai.build_learner(
    310     config,
    311     bags=bags,
    312     targets=targets,
    313     train_idx=train_idx,
    314     val_idx=val_idx,
    315     unique_categories=unique_categories,
    316     outdir=outdir,
    317 )
    318 return learner

File ~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/mil/train/_fastai.py:76, in build_learner(config, *args, **kwargs)
     74     return _build_clam_learner(config, *args, **kwargs)
     75 else:
---> 76     return _build_fastai_learner(config, *args, **kwargs)

File ~/miniconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/mil/train/_fastai.py:225, in _build_fastai_learner(config, bags, targets, train_idx, val_idx, unique_categories, outdir, device)
    223 # Prepare model.
    224 log.info(f"Training model {config.model_fn.__name__}, loss={config.loss_fn.__name__}")
--> 225 batch = train_dl.one_batch()
    226 model = config.model_fn(batch[0].shape[-1], batch[-1].shape[-1]).to(device)
    227 if hasattr(model, 'relocate'):

File ~/miniconda3/envs/slideflow/lib/python3.9/site-packages/fastai/data/load.py:171, in DataLoader.one_batch(self)
    170 def one_batch(self):
--> 171     if self.n is not None and len(self)==0: raise ValueError(f'This DataLoader does not contain any batches')
    172     with self.fake_l.no_multiproc(): res = first(self)
    173     if hasattr(self, 'it'): delattr(self, 'it')

ValueError: This DataLoader does not contain any batches

## Expected behavior
Completed training MIL model.

## Environment:
 - Slideflow Version (e.g., 1.0): 2.0
 - OS (e.g., Ubuntu): Ubuntu 
 - How you installed Slideflow (`pip`, source): pip
 - Python version: Python 3.9.16
 - CUDA/cuDNN version: 11.7
 - GPU models and configuration: V100
 - Any other relevant information:

**Comment by jamesdolezal** [comment]
Thanks for raising this issue. The error 'ValueError: This DataLoader does not contain any batches' makes me wonder if one of the datasets might be empty. What do you get when you run:

'''python
print(train_dataset.num_tiles)
print(val_dataset.num_tiles)
'''

**Comment by dakomura** [comment]
Thank you for the quick response. 
I got:
```
93095
42522
```

In `/bag_dir` directory, the number of .pt files is equivalent to the total number of samples, and none of the *files are empty. However, the file sizes range from 113Kb to 40Mb. Is 113Kb too small? Based on the slide processing report, it appears that the tiles have been extracted.

**Comment by jamesdolezal** [comment]
OK I think I may have figured out the problem - this error might be raised if one of the datasets has fewer samples than the MIL batch size (default batch size is 64). I've pushed an update that works around this issue. Do you have the ability to run from source? If so, can you update the `master` branch and see if the latest commit fixes the problem?

**Comment by dakomura** [comment]
Thank you for promptly fixing the problem. After updating, everything worked! I truly appreciate your incredible software!

**Comment by jamesdolezal** [comment]
Great! Glad to hear it. I'll roll this update into 2.0.1 later tonight.
