### ISSUE TITLE
couldn't run simclr

### ISSUE THREAD

**Issue by Meijian** [jamesdolezal/slideflow#251]
## Description

Hi James, here is a weird one. I have issues with simclr on two different platforms. 
One is on EC2 instance (py=3.7), when running from slideflow import simclr, it throws SyntaxError: invalid syntax. 
The other is when running actual training: P.train_simclr(args, dataset) on databricks (py=3.10), it threw error: AttributeError: 'LARSOptimizer' object has no attribute '_set_hyper'.

## To Reproduce
EC2
1. set tensorflow as backend
2. from slideflow import simclr

Databricks

import slideflow as sf
P = sf.load_project(rootpath)
dataset=P.dataset(tile_px=299, tile_um='10x')
from slideflow import simclr
args = simclr.get_args(
    temperature=0.1,
    learning_rate=0.3,
    train_epochs=100,
    image_size=299
)
P.train_simclr(args, dataset)

**EC2:**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/py3/env/lib64/python3.7/site-packages/slideflow/simclr/__init__.py", line 1, in <module>
    from .simclr.tf2 import (
  File "/root/py3/env/lib64/python3.7/site-packages/slideflow/simclr/simclr/tf2/__init__.py", line 23, in <module>
    from . import data as data_lib
  File "/root/py3/env/lib64/python3.7/site-packages/slideflow/simclr/simclr/tf2/data.py", line 188
    return image, label, *args
                         ^
SyntaxError: invalid syntax

**Databricks:**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/databricks/driver/slideflow/slideflow/project.py", line 3627, in train_simclr
    simclr.run_simclr(simclr_args, builder, model_dir=outdir, **kwargs)
  File "/databricks/driver/slideflow/slideflow/simclr/simclr/tf2/__init__.py", line 372, in run_simclr
    optimizer = model_lib.build_optimizer(
  File "/databricks/driver/slideflow/slideflow/simclr/simclr/tf2/model.py", line 33, in build_optimizer
    return lars_optimizer.LARSOptimizer(
  File "/databricks/driver/slideflow/slideflow/simclr/simclr/tf2/lars_optimizer.py", line 65, in __init__
    self._set_hyper("learning_rate", learning_rate)
AttributeError: 'LARSOptimizer' object has no attribute '_set_hyper'

## Environment:

EC2
 - Slideflow Version (e.g., 1.0): 2.0.1
 - OS (e.g., Ubuntu):  AMZ linux
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.7.16
 - CUDA/cuDNN version: 11.2/8
 - GPU models and configuration: Tesla T4
 - Any other relevant information: tensorflow 2.11.0

Databricks
 - Slideflow Version (e.g., 1.0): 2.0.1
 - OS (e.g., Ubuntu):  Ubuntu
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.10
 - CUDA/cuDNN version: 11.2/8
 - GPU models and configuration: Tesla T4
 - Any other relevant information: tensorflow 2.11.0

**Comment by jamesdolezal** [comment]
Thanks Meijian - we've actually just encountered this same problem recently, it's due to a Tensorflow version compatibility issue in Google's SimCLR implementation (https://github.com/google-research/simclr). We're working on defining the version limitation and seeing if we can expand upon their implementation to improve forward compatibility. In the meantime, you should be able to train SimCLR with Tensorflow 2.10. Once we define the version limitations, we'll update the documentation accordingly.

**Comment by Meijian** [comment]
Hi James, I downgraded tensorflow to 2.10.0 but still encountered the same issue when running on EC2 instance. Any thoughts?

<img width="713" alt="Screenshot 2023-04-13 235449" src="https://user-images.githubusercontent.com/13988409/231937654-f5608701-11ee-43e8-b3ab-6945f55d5a5f.png">

**Comment by jamesdolezal** [comment]
Sorry, to clarify - the second error you mentioned is due to a Tensorflow version issue. The first is a Python version incompatibility (that syntax is only valid in Python 3.8+).

We made Slideflow compatible with Python 3.7, but it appears that the SimCLR implementation by Google requires Python 3.8. We can probably modify their implementation to expand support to 3.7, but in the meantime, try using 3.8.

**Comment by jamesdolezal** [comment]
The SimCLR submodule has been updated to support Python 3.7 and Tensorflow 2.11+ in 72f8795. I will integrate these changes into a 2.0.2 patch release. Let me know if this fixes the issue on your end - if so, I will close.

**Comment by Meijian** [comment]
Hi James, that's awesome! I just tested it, it's still running but didn't give any error messages so far. I think you can close it. 
One thing I noticed is that it’s taking up a lot of memory. Any suggestions for users with limited computing resources? Thanks!

**Comment by jamesdolezal** [comment]
Are you seeing high utilization of system memory (RAM) or GPU memory (VRAM)? System RAM utilization should be fairly low - in my testing environment, SimCLR uses about 10 GB of memory. 

VRAM utilization is dependent upon a combination of the image size and batch size, arguments that are configured through `sf.simclr.get_args()`  (see [our docs](https://slideflow.dev/simclr/#slideflow.simclr.SimCLR_Args) for argument options and default values).  The default batch size of 512 can be decreased to whatever is appropriate for your available GPU memory.

**Comment by jamesdolezal** [comment]
With a first glance from these logs, it looks like a GPU memory issue. The `top` command is showing only 5.5 GB of system RAM usage, which is expected. 

Can you run `nvidia-smi` before and after executing your script? Sometimes there's a rogue, unkilled process hogging all the GPU memory. You'll want to confirm that your GPU memory utilization is close to 0% before starting any new scripts.

**Comment by Meijian** [comment]
Thank you for your suggestion, James. I will use the command next time. The process is still running, and it started generating some results. I will close this bug for now as the warning message is probably not related to the software itself. Thanks again!
