### ISSUE TITLE
[BUG] TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by billnjcn111** [jamesdolezal/slideflow#252]
## Description
Hi James,
A possible bug occurred when doing MIL training:

for train, val in splits:
    P.train_mil(
        config=config,
        outcomes=labels,
        train_dataset=train,
        val_dataset=val,
        bags='./ctranspath/'
    )

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_740/2999205598.py in <module>
      1 #training MIL:
      2 for train, val in splits:
----> 3     P.train_mil(
      4         config=config,
      5         outcomes=labels,

/opt/conda/lib/python3.8/site-packages/slideflow/project.py in train_mil(self, config, train_dataset, val_dataset, outcomes, bags, exp_label, **kwargs)
   3733         from .mil import train_mil
   3734 
-> 3735         return train_mil(
   3736             config,
   3737             train_dataset,

/opt/conda/lib/python3.8/site-packages/slideflow/mil/train/__init__.py in train_mil(config, train_dataset, val_dataset, outcomes, bags, outdir, exp_label, **kwargs)
     90     sf.util.write_json(config.json_dump(), join(outdir, 'mil_params.json'))
     91 
---> 92     return train_fn(
     93         config,
     94         train_dataset,

/opt/conda/lib/python3.8/site-packages/slideflow/mil/train/__init__.py in train_fastai(config, train_dataset, val_dataset, outcomes, bags, outdir, attention_heatmaps, **heatmap_kwargs)
    368         fastai.learner.Learner
    369     """
--> 370     from . import _fastai
    371 
    372     # Prepare bags.

/opt/conda/lib/python3.8/site-packages/slideflow/mil/train/_fastai.py in <module>
     11 
     12 from slideflow import log
---> 13 from slideflow.mil.data import build_clam_dataset, build_dataset
     14 from .._params import TrainerConfigFastAI, ModelConfigCLAM
     15 

/opt/conda/lib/python3.8/site-packages/slideflow/mil/data.py in <module>
     63 
     64 @dataclass
---> 65 class BagDataset(Dataset):
     66     """A dataset of bags of instances."""
     67 

/opt/conda/lib/python3.8/site-packages/slideflow/mil/data.py in BagDataset()
     66     """A dataset of bags of instances."""
     67 
---> 68     bags: Sequence[Iterable[Path]]
     69     """The `.h5` files containing the bags.
     70     Each bag consists of the features taken from one or multiple h5 files.

TypeError: 'ABCMeta' object is not subscriptable

## Environment:

 - Slideflow 2.0.1 (docker image torch 2.0.1)
 - OS: Ubuntu

**Comment by jamesdolezal** [comment]
This is an issue with the type hints - it looks like they're expecting Python 3.9 or greater, and you're using Python 3.8. I'll update these type hints and confirm that it resolves the issue.

**Comment by jamesdolezal** [comment]
Should be fixed on master. Let me know if this resolves the the problem, and if so I'll close this issue.

**Comment by billnjcn111** [comment]
Yes, this fixed it! thanks!
