### ISSUE TITLE
Loading Slides that Do Not Have OpenSlide Metadata

### ISSUE THREAD

**Issue by emmachancellor** [jamesdolezal/slideflow#253]
Images that do not contain OpenSlide metadata do not have an accessible 'level' parameter, which causes them to fail while being loaded into slideflow. The error tends to appear like this:

```
Error loading slide        
                    slide_name: VipsForeignLoadTiffFile     
                    does not support optional argument level    
                      . Skipping
```

To overcome this issue, @skochanny has edited the VIPSReader class and _thumb_from_slide() to access the 'n-pages'/'page' parameter in slides that do not contain OpenSlide metadata. We are working to check that this solution is robust.

**Comment by jamesdolezal** [comment]
Thanks, sounds great. There are multiple parts of the sf.slide submodule that read images using the `level` parameter, so I'm guessing it may be more than the thumbnail function that would need to be updated. We can review once you have an implementation ready.
