### ISSUE TITLE
AssertionError when using mil_fc_mc model

### ISSUE THREAD

**Issue by Meijian** [jamesdolezal/slideflow#254]
## Description

When training MIL with 'mil_fc_mc' it failed and threw AssertionError.

## To Reproduce
1. from slideflow.mil import mil_config

2. splits = train_dataset.kfold_split(
    k=4,
    labels='kmeans',
    preserved_site=False
)

3.
config = mil_config('mil_fc_mc', lr=1e-4, epochs=3, batch_size=32, bag_size=1000)
for train, val in splits:
  P.train_mil(
    config=config,
    outcomes='kmeans',
    train_dataset=train,
    val_dataset=val,
    bags='/dbfs/mnt/gmb-ds-dbpoc/megu/pdac/imagenet/bag_directory/',
    attention_heatmaps=False,
    cmap='magma',
    interpolation=None
  )

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
File <command-1161367335775475>:10
      8 config = mil_config('mil_fc_mc', lr=1e-4, epochs=3, batch_size=32, bag_size=1000)
      9 for train, val in splits:
---> 10   P.train_mil(
     11     config=config,
     12     outcomes='kmeans',
     13     train_dataset=train,
     14     val_dataset=val,
     15     bags='/dbfs/mnt/gmb-ds-dbpoc/megu/pdac/imagenet/bag_directory/',
     16     attention_heatmaps=False,
     17     cmap='magma',
     18     interpolation=None
     19   )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/project.py:3735, in Project.train_mil(self, config, train_dataset, val_dataset, outcomes, bags, exp_label, **kwargs)
   3701 r"""Train a multi-instance learning model.
   3702 
   3703 Args:
   (...)
   3731 
   3732 """
   3733 from .mil import train_mil
-> 3735 return train_mil(
   3736     config,
   3737     train_dataset,
   3738     val_dataset,
   3739     outcomes,
   3740     bags,
   3741     outdir=join(self.root, 'mil'),
   3742     exp_label=exp_label,
   3743     **kwargs
   3744 )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/mil/train/__init__.py:92, in train_mil(config, train_dataset, val_dataset, outcomes, bags, outdir, exp_label, **kwargs)
     89 outdir = sf.util.create_new_model_dir(outdir, exp_label)
     90 sf.util.write_json(config.json_dump(), join(outdir, 'mil_params.json'))
---> 92 return train_fn(
     93     config,
     94     train_dataset,
     95     val_dataset,
     96     outcomes,
     97     bags,
     98     outdir=outdir,
     99     **kwargs
    100 )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/mil/train/__init__.py:382, in train_fastai(config, train_dataset, val_dataset, outcomes, bags, outdir, attention_heatmaps, **heatmap_kwargs)
    379     all_bags = np.array(bags)
    381 # Build learner.
--> 382 learner = build_fastai_learner(
    383     config,
    384     train_dataset,
    385     val_dataset,
    386     outcomes,
    387     bags=all_bags,
    388     outdir=outdir,
    389 )
    391 # Train.
    392 _fastai.train(learner, config)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/mil/train/__init__.py:312, in build_fastai_learner(config, train_dataset, val_dataset, outcomes, bags, outdir)
    309 log.info("Validation dataset: {} bags (from {} slides)".format(len(val_idx), len(val_slides)))
    311 # Build FastAI Learner
--> 312 learner = _fastai.build_learner(
    313     config,
    314     bags=bags,
    315     targets=targets,
    316     train_idx=train_idx,
    317     val_idx=val_idx,
    318     unique_categories=unique_categories,
    319     outdir=outdir,
    320 )
    321 return learner

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/mil/train/_fastai.py:74, in build_learner(config, *args, **kwargs)
     53 """Build a FastAI learner for training an MIL model.
     54 
     55 Args:
   (...)
     71 
     72 """
     73 if isinstance(config.model_config, ModelConfigCLAM):
---> 74     return _build_clam_learner(config, *args, **kwargs)
     75 else:
     76     return _build_fastai_learner(config, *args, **kwargs)

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/mil/train/_fastai.py:147, in _build_clam_learner(config, bags, targets, train_idx, val_idx, unique_categories, outdir, device)
    145 log.info(f"Training model {config.model_fn.__name__}, loss={config.loss_fn.__name__}")
    146 batch = train_dl.one_batch()
--> 147 model = config.model_fn(size=[batch[0][0].shape[-1], 256, 128], n_classes=batch[-1].shape[-1])
    148 model.relocate()
    150 # Loss should weigh inversely to class occurences.

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/mil/models/mil_fc.py:74, in MIL_fc_mc.__init__(self, size, dropout, n_classes, top_k, gate)
     65 def __init__(
     66     self,
     67     size: Union[str, List[int]] = "small",
   (...)
     71     gate: bool = True,
     72 ):
     73     super().__init__()
---> 74     assert n_classes > 2
     76     self.size = self.sizes[size] if isinstance(size, str) else size
     78     fc = [nn.Linear(self.size[0], self.size[1]), nn.ReLU()]

AssertionError: 

## Environment:

 - Slideflow Version (e.g., 1.0): 2.0.2
 - OS (e.g., Ubuntu): Ubuntu in Databricks
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.9
 - CUDA/cuDNN version:
 - GPU models and configuration: T4
 - Any other relevant information:

**Comment by jamesdolezal** [comment]
The `mil_fc_mc` model is a multi-class model used for training models with >2 outcome classes. How many outcome categories do you have for the labels 'kmeans'?

**Comment by Meijian** [comment]
Thank you, James. That's it. My label only has two classes. I was running through all the methods that MIL provides and didn't pay attention to the 'mc' suffix. On that note, does MIL support training on continuous outcomes?

**Comment by jamesdolezal** [comment]
No problem - neither the error message nor documentation were clear about this, so I'll update both.

MIL training currently only supports categorical outcomes, but thankfully it will be very straightforward to add support for continuous and time-to-event (e.g. Cox Proportional Hazards) outcomes. Both are planned for the next feature release (2.1).

**Comment by Meijian** [comment]
That's awesome news. One more random thought, would guys be able to include a small but real-world sample image set in future releases? I see it will have at least three benefits, 1) help users test parameters before applying to a bigger set, 2) benchmark the model performance, and 3) you guys can share some best practices using the package. I think that would be helpful to new users.

**Comment by jamesdolezal** [comment]
We do provide three example projects out-of-the-box (https://slideflow.dev/quickstart/), with the goal of helping new users to quickly get started on an example dataset from either lung cancer, breast cancer, or thyroid cancer. Or do you mean a pre-processed TFRecord dataset, rather than slides?

**Comment by Meijian** [comment]
Gosh, yes, I remember seeing these datasets in the beginning. Somehow I thought they were only used to demonstrate how to set up the project since I don't see them mentioned in other parts of the documentation. I will try those data sets to benchmark. Thanks.

**Comment by Meijian** [comment]
Actually, I just encountered this error. It looks like the link to the JSON file doesn't exist anymore. Any thoughts?
![image](https://user-images.githubusercontent.com/13988409/232948292-9cb09916-2f08-4a11-a81a-b35ab9c4f57c.png)

**Comment by jamesdolezal** [comment]
Whoops! I just renamed our `dev` branch a couple hours ago and forgot this link was hard-coded. I just restored the `dev` branch, and I've updated this code to point to `master`. Try it now!

**Comment by Meijian** [comment]
Works now. Thanks!
