### ISSUE TITLE
TypeError: load_model() got an unexpected keyword argument 'cpu'

### ISSUE THREAD

**Issue by Meijian** [jamesdolezal/slideflow#256]
## Description

Sorry for more work, but got this error when running segment_slide(): "TypeError: load_model() got an unexpected keyword argument 'cpu'".

## To Reproduce
from slideflow.cellseg import segment_slide
segmentation = segment_slide(
    '/path/to/my.svs',
    model='cyto2',
    diam_um=12,
    window_size=256,
    downscale=2,
    gpus=4
)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/cellseg/__init__.py", line 559, in segment_slide
    cp.net.load_model(cp.pretrained_model[0], cpu=(not cp.gpu))  # Modify to accept different models
TypeError: load_model() got an unexpected keyword argument 'cpu'
## Environment:

 - Slideflow Version (e.g., 1.0): 2.0.2
 - OS (e.g., Ubuntu): Ubuntu
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.9
 - CUDA/cuDNN version:
 - GPU models and configuration: T4
 - Any other relevant information:

**Comment by jamesdolezal** [comment]
Hi Meijian - this is due to an API change in cellpose from 2.1 to 2.2. Please downgrade the cellpose package to <2.2:

```
pip install "cellpose<2.2"
```

In the meantime, I'll fix the package version to require cellpose < 2.2 until I'm able to fully test their new version.

**Comment by Meijian** [comment]
Got it. I will try and let you know.

**Comment by jamesdolezal** [comment]
The cellpose version has been pinned to <2.2 starting in 2.0.3
