### ISSUE TITLE
[BUG] missing MPP in Hamamatsu ndpi file

### ISSUE THREAD

**Issue by dakomura** [jamesdolezal/slideflow#258]
## Description
I'm trying to read an ndpi file and execute 
```
dataset.extract_tiles(qc='otsu')
``` 
However, I'm encountering the following error, causing the process to skip:
```
ERROR Error loading slide /wsi/nanozoomer/meningioma/Menigioma_add3/2021-11-11_09.59.06.ndpi: Slide
2021-11-11_09.59.06 missing MPP (openslide.mpp-x). Skipping
```
Is there a way to load the MPP from metadata or specify it manually?

## Environment:

Slideflow
OS: Ubuntu
Version: 2.0.3-post1
Backend: tensorflow
Slide Backend: cucim
https://slideflow.dev/

**Comment by jamesdolezal** [comment]
NDPI files require the Libvips slide reading backend, as cuCIM only works with SVS and TIFF files. Ensure you have libvips installed, then set the environmental variable `SF_SLIDE_BACKEND` to `libvips`:

```
export SF_SLIDE_BACKEND=libvips
```

That should resolve the issue. If not, I can provide instructions for how to manually specify the MPP (although this will still require libvips)

**Comment by dakomura** [comment]
Thank you for the very quick reply!

It worked by setting the environmental variable.

I truly appreciate your help.

**Comment by jamesdolezal** [comment]
In this case, it can't find a "20x" magnification layer in the file - the closest magnification it can find is 22.6x. This is due to variations in how different slide scanners report optical magnication (See our paper, Figure 2B: https://arxiv.org/pdf/2304.04142.pdf)

You can overcome this by changing tile_um from "20x" to "22x".

**Comment by dakomura** [comment]
Thank you very much!
The issue has been resolved.

Please keep up the great work on this project!
