### ISSUE TITLE
[BUG] "CLAM_SB" model cannot deal with less than 8 tiles

### ISSUE THREAD

**Issue by p024eb** [jamesdolezal/slideflow#259]
## Description
When i used "CLAM_SB" model for MIL training, I got this error.
`RuntimeError: Error selecting top_k from sample with shape torch.Size([1, 4]). Verify that all slides have at least 8 tiles (min_tiles=8). Error: selected index k out of range`

It was supposed to be fixed if I adjusted the top_k num.

I tried setting "B (int) – Number of positive/negative patches to sample for instance-level training. Defaults to 8." from ModelConfigCLAM to 4 but I got the same error.

Is this a bug, or which parameter should I change?

## Environment:

 - Slideflow Version : 2.0.3-post
 - OS : Ubuntu
 - Python version:3.8
 - Backend: torch

**Comment by jamesdolezal** [comment]
What this error is trying to convey is that the CLAM modules need at minimum 8 tiles per slide (or whatever the B parameter is set to). So we need to provide it a dataset that has filtered out TFRecords with fewer tiles than that. You can do this by supplying the min_tiles argument when creating your dataset:

```
project = sf.Project(...)

dataset = project.dataset(..., min_tiles=8)
```

Then use that dataset for training CLAM.

I'll see if I can improve the wording of the error function and documentation to make this more clear.

**Comment by p024eb** [comment]
Thank you for the rapid reply, James!
The error was solved after I  filtered my dataset like the above.
