### ISSUE TITLE
[BUG] missing MPP (openslide.mpp-x). Skipping

### ISSUE THREAD

**Issue by cswpy** [jamesdolezal/slideflow#266]
## Description
I am extracting the tiles from `.ndpi` files using Project by running the following code.

```python
full_dataset.extract_tiles(save_tfrecords=True, enable_downsample=False)
```

However, I am encountering the following error.
```bash
Error loading slide                                                                            
                   *.ndpi: Slide * missing MPP (openslide.mpp-x). Skipping
```

I read about issue #258 and exported the environmental variables as following

```bash
export SF_SLIDE_BACKEND=libvips
```
and restarted the kernel, the issue persisted.

## Environment:

 - Slideflow Version (e.g., 1.0): 2.0.3-post1
 - OS (e.g., Ubuntu): Ubuntu
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.10.9
 - CUDA/cuDNN version: cuda_11.7.r11.7/compiler.31442593_0
 - GPU models and configuration: NVIDIA T4
 - Any other relevant information: tensorflow backend, using Libvips

**Comment by jamesdolezal** [comment]
Thanks for raising this issue. Can you run the following code at the top of your script, confirm that the slide backend has been set appropriately?

`sf.about()`

Does this happen with all of your slides, or only some? How did you install Libvips?

**Comment by jamesdolezal** [comment]
If you're running from a Jupyter notebook, you'd need to run that command from the terminal just before starting the notebook:

```
export SF_SLIDE_BACKEND=libvips
jupyter lab
```

Alternatively, you can use this syntax;

```
SF_SLIDE_BACKEND=libvips jupyter lab
```

Finally, you can try adding the following line at the top of your script, before importing slideflow:

```
import os
os.environ['SF_SLIDE_BACKEND'] = 'libvips'
```
