### ISSUE TITLE
Improving Studio's MPP functionality and feature view

### ISSUE THREAD

**Issue by skochanny** [jamesdolezal/slideflow#270]
## Feature
In Slideflow Studio, I would like to be able to capture image views at a particular MPP. However, when I zoom in & out the MPP can ever so slightly change. I would like to be able to set the MPP manually somewhere so that I have the option of being able to work at a precise, replicable resolution. 

Additionally, it would be nice to have an option to hide the x & y coordinates + MPP from view, like we can do with the thumbnail & scale. This occurs by unchecking a box in the View dropdown menu. Currently, when exporting a capture of a slide view, a black bar with the x, y and mpp is saved along with the image. 
![image](https://github.com/jamesdolezal/slideflow/assets/46627872/baae724d-d464-491c-aee6-f3ea310a9324)

**Comment by jamesdolezal** [comment]
Thanks for this suggestion. I've added some changes to the `dev-2.1` branch:

- Exporting an image of the main view now crops out the status bar. 
- You can now zoom to a specific MPP with View -> Zoom to MPP, or by pressing Ctrl + /

**Comment by jamesdolezal** [comment]
Implemented in `2.1.0`
