### ISSUE TITLE
[BUG] Documentation for Project.extract_tiles mentions wrong default value for num_threads

### ISSUE THREAD

**Issue by sebp** [jamesdolezal/slideflow#273]
## Description

The API docs for `Project.extract_tiles` mentions that the default value for `num_threads` is 4:
https://github.com/jamesdolezal/slideflow/blob/ee85cede86565db04ccd7c77f157fd320c947016/slideflow/project.py#L1617-L1618
However, the arguments are forwarded to `Dataset.extract_tiles`, which uses the number of CPU cores as default:
https://github.com/jamesdolezal/slideflow/blob/ee85cede86565db04ccd7c77f157fd320c947016/slideflow/dataset.py#L1564-L1565

The API docs for `Dataset.extract_tiles` mentions the following:
https://github.com/jamesdolezal/slideflow/blob/ee85cede86565db04ccd7c77f157fd320c947016/slideflow/dataset.py#L1453-L1458

## Expected behavior

The API docs of `Project.extract_tiles` should be consistent with those of  `Dataset.extract_tiles`.

## Environment:

 - Slideflow Version: 2.0
 - OS (e.g., Ubuntu):  Ubuntu 20.04.5 LTS
 - How you installed Slideflow (`pip`, source): Docker
 - Python version:  3.8.10

**Comment by jamesdolezal** [comment]
Thanks for reporting this. I have updated the docstring for Project.extract_tiles() to match Dataset.extract_tiles(), as there were some changes to the latter that hadn't been transferred over to the former. These changes will be reflected in the online documentation the next time we do a documentation build update, probably in a week or two.
