### ISSUE TITLE
Typo in documentation regarding implementation of Cox Proportional Hazards

### ISSUE THREAD

**Issue by sebp** [jamesdolezal/slideflow#276]
## Description

The documentation says

https://github.com/jamesdolezal/slideflow/blob/188e219d1baa5e709d5bb04e287d86986938745f/docs-source/source/training.rst?plain=1#L200

## Expected behavior

Documentation should clarify whether implementation is missing for PyTorch or Tensorflow.

**Comment by jamesdolezal** [comment]
Thanks for opening an issue. I don't completely understand the question, however - the documentation states that CPH models are unavailable with PyTorch. How can the wording be improved?

**Comment by sebp** [comment]
I guess typo is the wrong word. It would be clearer when saying that 
it's only available in Tensorflow and the PyTorch implementation is in 
development, rather then saying for which framework it is unavailable.

**Comment by jamesdolezal** [comment]
Got it. Thanks for the suggestion, I will update the wording in this section of the documentation.

**Comment by jamesdolezal** [comment]
The documentation has been updated to state:

```
CPH models are currently only available with the Tensorflow backend. PyTorch support for CPH outcomes is in development.
```
