### ISSUE TITLE
Protobuf dependency conflict

### ISSUE THREAD

**Issue by sebp** [jamesdolezal/slideflow#289]
slideflow specifies
https://github.com/jamesdolezal/slideflow/blob/e512da1a2ccac323e6b7a84b91bfc91a66771a67/setup.py#L114

whereas tensorflow-metadata (a dependency of tensorflow-datasets), [specifies](https://github.com/tensorflow/metadata/blob/b61c02b37ec263d771bb140a14a7308b5255a8d0/setup.py#L130)
```
 'protobuf>=3.20.3,<5',
```

Since pip is bad dealing with conflicts, installing `tensorflow-datasets` after `slideflow` will effectively upgrade protobuf to version 4, which breaks slideflow.

To make matters worse, tensorflow 2.9.3, which the docker image is based on, [specifies](https://github.com/tensorflow/tensorflow/blob/a5ed5f39b675a1c6f315e0caf3ad4b38478fa571/tensorflow/tools/pip_package/setup.py#L97)
```
'protobuf >= 3.9.2, < 3.20',
```

Requiring `tensorflow_datasets<=4.9.0` should help.

**Comment by jamesdolezal** [comment]
Thanks for raising the issue - `protobuf` version issues are tricky. The TFRecord reader used in the PyTorch backend uses `protobuf` (this is where the <3.20.2 requirement comes from), but I don't believe `protobuf` is used in the Tensorflow backend. I'll mess around with pinning the `tensorflow_datasets` version as you suggest and see if that helps. 

This weekend is the American Society of Clinical Oncology (ASCO) annual meeting, so it may be a few days before someone from our team addresses this.

**Comment by jamesdolezal** [comment]
Thanks again for raising the issue.
Slideflow requires protobuf <= 3.20.* for TFRecord reading in the PyTorch backend. In 1c4aa6d, I updated the versions in setup.py to slightly improve compatibility:

- `protobuf<=3.20.2` updated to `<3.20` (allows 3.20.3)
- `tensorflow_datasets` updated to `<4.9.0`

These version requirements will be reflected in the upcoming 2.1 version release.
