### ISSUE TITLE
mil_config model_size argument being silently thrown out by default

### ISSUE THREAD

**Issue by quark412** [jamesdolezal/slideflow#294]
Hi! I wanted to say thanks for writing this package, it's very useful :)

This is somewhere in between a bug report and a feature request, but currently the model_size argument to mil_config is not being used by default. (Which explains why varying it never seemed to make much difference in any of the hyperparameter searches I ran!)

The source code for mil_config, from [here](https://github.com/jamesdolezal/slideflow/blob/master/slideflow/mil/_params.py), looks as follows (with line numbers included):

```
8 def mil_config(model: Union[str, Callable], trainer: str = 'fastai', **kwargs):
...
33    if trainer == 'fastai':
34        return TrainerConfigFastAI(model=model, **kwargs)
```
Then in the TrainerConfigFastAI class:
```
150             self.model_config = ModelConfigCLAM(model=model, **kwargs)
```
Finally, in the ModelConfigCLAM class:
```
322         for argname, argval in dict(locals()).items():
323            setattr(self, argname, argval)
```
So the model_size is being stored as config.model_config.model_size. Then lines 102-108 in the mil eval code, from [here](https://github.com/jamesdolezal/slideflow/blob/master/slideflow/mil/eval.py), are as follows. Since the default is TrainerConfigFastAI, the first if statement is skipped by default.
```
    if isinstance(config, TrainerConfigCLAM):
        config_size = config.model_fn.sizes[config.model_config.model_size]
        model = config.model_fn(size=[n_features] + config_size[1:])
    elif isinstance(config.model_config, ModelConfigCLAM):
        model = config.model_fn(size=[n_features, 256, 128])
    else:
        model = config.model_fn(n_features, n_out)
```

Similarly in the train code used in the default case (when no trainer input is given), from [here](https://github.com/jamesdolezal/slideflow/blob/master/slideflow/mil/train/_fastai.py):

```
147     model = config.model_fn(size=[batch[0][0].shape[-1], 256, 128], n_classes=batch[-1].shape[-1])
```

So the size does not actually depend on the model_size by default.

I haven't chased down whether or not the model_size is thrown out if you instead use the legacy CLAM trainer. 

In the long run it would be nice for this to be fixed, but in the short run perhaps there could be an error message or warning stating that model_size isn't being used.

**Comment by jamesdolezal** [comment]
Yikes - thank you for discovering this! We'll get a patch out in the next couple of days.

**Comment by jamesdolezal** [comment]
Patch is up on `master` - let me know if this also works on your end. I'll do some additional testing and include it in the next patch release, 2.0.6.

**Comment by quark412** [comment]
Yes, works now! Thanks!
