### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'multi_gpu'

### ISSUE THREAD

**Issue by ltzg** [jamesdolezal/slideflow#298]
Multiple GPUs cannot be used with TensorFlow, one GPU is OK

hp = sf.ModelParams(
    tile_px=256,
    tile_um=256,
    # model='densenet',
    batch_size=32,
    epochs=[10],
    multi_gpu=True
)
Traceback (most recent call last):
  File "/home/xl/下载/pycharm-community-2023.1.2/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/home/xl/anaconda3/envs/sftf/lib/python3.9/site-packages/slideflow/model/tensorflow.py", line 148, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'multi_gpu'

TensorFlow==2.10

**Comment by jamesdolezal** [comment]
Hi Itzg,

The `multi_gpu=True` argument should be used for `Project.train()`, not `ModelParams`:

```
hp = sf.ModelParams(...)
Project.train(..., multi_gpu=True)
```

**Comment by ltzg** [comment]
Thank you very much for your reply. I got an new  ErrorTraceback (most recent call last):  File "/home/xl/下载/pycharm-community-2023.1.2/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode    coro = func()  File "<input>", line 1, in <module>  File "/home/xl/anaconda3/envs/sftf/lib/python3.9/site-packages/slideflow/project.py", line 3426, in train    self._train_hp(  File "/home/xl/anaconda3/envs/sftf/lib/python3.9/site-packages/slideflow/project.py", line 713, in _train_hp    self._train_split(dataset, hp, val_settings, s_args)  File "/home/xl/anaconda3/envs/sftf/lib/python3.9/site-packages/slideflow/project.py", line 937, in _train_split    project_utils._train_worker(  File "/home/xl/anaconda3/envs/sftf/lib/python3.9/site-packages/slideflow/project_utils.py", line 147, in _train_worker    results = trainer.train(train_dts, val_dts, **training_kw)  File "/home/xl/anaconda3/envs/sftf/lib/python3.9/site-packages/slideflow/model/tensorflow.py", line 1763, in train    atexit.register(strategy._extended._collective_ops._pool.close)AttributeError: &apos;CollectiveAllReduce&apos; object has no attribute &apos;_pool&apos;
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            James ***@***.***>
            
        
      
      
        
         Date 
        
        
        6/20/2023 08:56
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [jamesdolezal/slideflow] TypeError: __init__() got an unexpected keyword argument 'multi_gpu' (Issue #298)
        
      
    
  

Hi Itzg,
The multi_gpu=True argument should be used for Project.train(), not ModelParams:
hp = sf.ModelParams(...)
Project.train(..., multi_gpu=True)

**Comment by jamesdolezal** [comment]
The above error looks like a multiprocessing issue. Restarting the development environment or python kernel should fix the problem.
