### ISSUE TITLE
[Documentation] Optimization space documentation missing

### ISSUE THREAD

**Issue by luiscarm9** [jamesdolezal/slideflow#308]
## Description
The documentation for the methods sf.util.shallow_search_space() and sf.utils.broad_search_space() needs to be included.

## Expected behaviour
In the documentation, these methods are mentioned for parameter optimization. But the parameters and their different usage could be more precise for me.

## Environment:

 - Slideflow Version: 2.1.0
 - OS: Ubuntu
 - How you installed Slideflow: PIP
 - Python version: 3.10.6
 - CUDA/cuDNN version: 12.1
 - GPU models and configuration: Quadro RTX4000

**Comment by jamesdolezal** [comment]
Thank you for this - the docstrings for these functions are already written (see https://github.com/jamesdolezal/slideflow/blob/master/slideflow/util/smac_utils.py), although our sphinx autodocs did not include these in the docs during build. I will update the autodocs config to include these and re-build the documentation.

**Comment by luiscarm9** [comment]
Perfect, thanks for the fast reply.
Should I use the Documentation Tag if I find further suggestions?

**Comment by jamesdolezal** [comment]
Yes, the Documentation tag would be best for tracking these types of issues. Thanks again the feedback!
