### ISSUE TITLE
[BUG] Providing extractor argument to sf.mil.eval.predict_slide throws error

### ISSUE THREAD

**Issue by bplee** [jamesdolezal/slideflow#310]
## Description
If you provide a feature extractor argument to `sf.mil.eval.predict_slide`, `detected_normalizer` variable never gets assigned

## To Reproduce
1. Provide a feature extractor argument to the `predict_slide` function

```
>>> y_pred, y_att = predict_slide(model, wsi, feat_extractor)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/slideflow/mil/eval.py", line 198, in predict_slide
    if detected_normalizer is not None and normalizer is not None:
UnboundLocalError: local variable 'detected_normalizer' referenced before assignment
```

## Environment:

 - Slideflow Version (e.g., 1.0): 2.1.0
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.8.12

**Comment by jamesdolezal** [comment]
Thanks for this bug report. I'll have a patch out later today!
