### ISSUE TITLE
[BUG] Unable to tile WSIs

### ISSUE THREAD

**Issue by ajr82** [jamesdolezal/slideflow#318]
## To Reproduce
This is my code that I am running. On running it there are no tiles generated. The code stops without an error.  

OPENSLIDE_PATH = 'C:/Git/openslide-20230414/bin'
import os
if hasattr(os, 'add_dll_directory'):
    # Windows
    with os.add_dll_directory(OPENSLIDE_PATH):
        import openslide
else:
    import openslide
	
import pandas as pd
import numpy as np
from openslide import OpenSlide
from multiprocessing import Pool, Value, Lock
import os
from skimage.color import rgb2hsv
from skimage.filters import threshold_otsu
from skimage.io import imsave, imread
from skimage.exposure.exposure import is_low_contrast
from skimage.transform import resize
from scipy.ndimage import binary_dilation, binary_erosion
import argparse
import logging
import pickle
import h5py

import slideflow as sf

P = sf.create_project(
  root='C:/Git/project/',
  annotations="C:/Git/project/test.csv",
  slides='C:/Git/slides/',
)
P.add_source(
  name="MyProject",
  slides="C:/Git/slides/",
  roi="C:/Git/project/slides/roi/directory",
  tiles="C:/Git/project/slides/tiles/directory",
  tfrecords="C:/Git/project/slides/tfrecords/directory"
)
dataset = sf.Dataset(
    config='C:/Git/project/datasets.json',
    sources=['MyProject'],
    annotations='C:/Git/project/test.csv',
    tile_px=299,
    tile_um='40x'
)
dataset.extract_tiles(tile_px=299, tile_um='40x')
dataset.num_tiles

## Expected behavior

Tiles of all WSI to be generated.

## Environment:

 - Slideflow Version (e.g., 1.0): 2.1.0
 - OS (e.g., Ubuntu): Win 11
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.10
 - CUDA/cuDNN version: 11.8
 - GPU models and configuration: RTX 4070
 - Any other relevant information:

**Comment by jamesdolezal** [comment]
Thanks for opening this issue. I have a couple of initial questions:

- Have you installed libvips, cucim, or both? (see: https://slideflow.dev/installation/#cucim-vs-libvips)
- What is the output from the following:

```python
import slideflow as sf
sf.about()
```

**Comment by jamesdolezal** [comment]
I'm going to go ahead and close this issue due to inactivity - please respond here if you would like me to re-open.
