### ISSUE TITLE
Environment file environment.yml update for slideflow version 2

### ISSUE THREAD

**Issue by sz3029** [jamesdolezal/slideflow#321]
## Description
I'm trying to set up my conda for the new slideflow version (v2.1.0). I looked at the provided environment.yml file, but in line #178 it still says slideflow==1.3.2 so I guess the environment file wasn't updated? Could you update it with the lastest environment.yml for v2.1.0? Thank you

**Comment by jamesdolezal** [comment]
Thank you! We've used this environment recently as a base for building a 2.1.0 environment, there are a couple of minor package version updates required. I'll get an updated environment YAML file uploaded today or tomorrow.

**Comment by sz3029** [comment]
Hi is there any update :)

**Comment by jamesdolezal** [comment]
Thanks again for the suggestion! The provided environment has been updated for Slideflow 2.1.1. Let us know if you have issues or concerns with this updated environment, and if so, I will re-open this issue.
