### ISSUE TITLE
Bootstrap 

### ISSUE THREAD

**Issue by mnezaf** [jamesdolezal/slideflow#333]
## Feature
Using bootstrapping split for MIL model

## Pitch

Thank you for the recent version, very helpful documenation! 
We are training attMIL model using kfold cross validation. We realized that there is a huge performance differences in between folds. We plan to try bootsrapping as well, but the training iteration just done once. Is there any way to specify the number of training and validation splits in bootstrap strategy?
Thanks

**Comment by jamesdolezal** [comment]
Hi! Yes, this is possible to do. Following [Tutorial 8](https://slideflow.dev/tutorial8/), you would replace the the following line:

```python
train, val = dataset.split(labels='er_status_by_ihc', val_fraction=0.3)
```

with:

```python
for _ in range(n_iterations):
    train, val = dataset.split(..., val_fraction=0.3)
    # Train MIL function with this bootstrap split
```

And that's it!
