### ISSUE TITLE
[HistoSSL/heatmaps] MIL model attention heatmaps display bright lines when use histoSSL as the feature extractor

### ISSUE THREAD

**Issue by sz3029** [jamesdolezal/slideflow#336]
## Feature
The newly added pre-trained histoSSL model is very helpful. However, I have observed bright lines on the heatmaps, they are common on instances with 20x and 40x mag levels, and visible with 10x. The lines were not from the image itself, and were not present on heatmaps trained by models using other feature extractors (resnet50, etc. al.). I'm wondering if there's something to do with the heatmap methods. Below are some examples:

* Heatmap examples for 20x, 40x, feature extractor = histoSSL, a true negative case:

<img width="762" alt="Screenshot 2023-11-16 at 2 23 33 PM" src="https://github.com/jamesdolezal/slideflow/assets/90408067/8febca9c-24cc-404c-9827-f7d99f4c4f74">

<img width="789" alt="Screenshot 2023-11-16 at 2 22 00 PM" src="https://github.com/jamesdolezal/slideflow/assets/90408067/9938ad76-4d20-48b6-846a-16aafc303ec9">

* Heatmap examples for 20x, 40x, feature extractor = resnet50, a true negative case:

<img width="771" alt="Screenshot 2023-11-16 at 2 25 39 PM" src="https://github.com/jamesdolezal/slideflow/assets/90408067/19cc0c90-46cc-4756-93be-1cac0c0812cd">

<img width="738" alt="Screenshot 2023-11-16 at 2 26 51 PM" src="https://github.com/jamesdolezal/slideflow/assets/90408067/5125e582-db7a-435c-864b-ba51ad9766ce">

(Tiles are from the same source) 

## Pitch
No bright lines on heatmaps. 

## Alternatives
1. Editing the heatmap methods (if the problem is due to how the heatmap is ploted)
2. Some normalization of the scores might help (log transformation, etc. al.)

**Comment by jamesdolezal** [comment]
Hmm - first guess is that this looks like focus banding issues (some slide scanners have a propensity to generate out of focus regions in repeating bands, as is shown here). What do you see when you zoom in at high resolution at these transition points? Is there anything obvious to the naked eye with respect to focus, tiling, etc?

**Comment by sz3029** [comment]
Thank you for the quick reply. I was suspecting that when I first saw the heatmaps. But I inspected the scans at 20x and 40x and I didn't see visible bands. But if you haven't seen this before then it might be a scanner issue :(

at ~5x:
<img width="1180" alt="Screenshot 2023-11-16 at 3 15 55 PM" src="https://github.com/jamesdolezal/slideflow/assets/90408067/22d49225-17a7-4ccf-878b-d51386e8edae">

at ~40x:
<img width="1180" alt="Screenshot 2023-11-16 at 3 15 26 PM" src="https://github.com/jamesdolezal/slideflow/assets/90408067/91560d05-9520-4e0a-86cf-4619325bb999">

**Comment by sz3029** [comment]
Hi James, thank you for the advice. I run with the code above on several images. I think for mag. level >20x there are some possible bands showing up on the deepfocus trained image.

![download-2](https://github.com/jamesdolezal/slideflow/assets/90408067/fe5ba5a9-f457-4cc7-9079-327d9af7528c)

I think I will find some way to normalized it. Thank you for your help.
