### ISSUE TITLE
Is slideflow studio supported on Windows?

### ISSUE THREAD

**Issue by LeventAksakal** [jamesdolezal/slideflow#361]
I'm a rookie so please execuse me. Both python packages for libvips and cuCIM doesn't support windows. How can I use sf-studio? 
Thanks a lot.

**Comment by Phues** [comment]
I was not able to run it on windows, so I used docker instead and it works, refer to this for more info: 
https://github.com/jamesdolezal/slideflow/issues/352

**Comment by LeventAksakal** [comment]
I installed the vips binary any added it to PATH. Then python -m slideflow.studio runs the GUI.
