### ISSUE TITLE
Cannot use predict slide for MIL model

### ISSUE THREAD

**Issue by jziggles** [jamesdolezal/slideflow#365]
## Description
The "predict_slide" function in slideflow studio does not work.  I have been using the magnification value in the tile_um variable during tile extraction.  The slides (TCGA library for ER status by IHC) appear to have different tile_um sizes ranging from 497 to 505 uM when they are loaded in slideflow.  Is this variable nature the problem? 

## To Reproduce
1. Load project
2. Load MIL model
3. Load slide that has been run in MIL model w/ attention values
4.  Click predict slide

Error message in slideflow studio 
MIL model tile size (tile_px = 500, tile_um = 10x) does not match the currently loaded slide (tile_px = 500, tile_um=497)

## Expected behavior

I want to be able to predict the slide and overlay attention values. 

## Environment:

 - Slideflow Version (e.g., 1.0): 2.3.1
 - OS (e.g., Ubuntu): Red Hat 8
 - How you installed Slideflow (`pip`, source): pip 
 - Python version: 3.9

**Comment by jamesdolezal** [comment]
Thanks for raising this, and I apologize it took our team so long to address. This is a bug, we'll get it fixed and applied to our next release.

**Comment by jamesdolezal** [comment]
A possible fix has been applied to the `dev` branch and will enter our testing queue.

**Comment by jziggles** [comment]
Thanks James I appreciate it - really incredible work on this package.
