### ISSUE TITLE
[BUG] cannot  download preconfigured dataset

### ISSUE THREAD

**Issue by WNZhao1988** [jamesdolezal/slideflow#370]
## Description
When I trying to download the preconfigured dataset I got the following error, it seemed the package went something wrong:

![image](https://github.com/jamesdolezal/slideflow/assets/76765350/a1489e15-5a66-45c5-bbf6-9b2c65ea864c)

My code and the error message looks like above, could you may be help explain why this happened?

Thank you!

**Comment by BilalAhmd-24** [comment]
Hey there,
Just use it as function rather than the project name.
sf.project.ThyroidBRS()
It needs to be corrected in tutorials.
Peace.

**Comment by jamesdolezal** [comment]
Thanks, @BilalAhmd-24! Tutorial will be updated.
