### ISSUE TITLE
[QUESTION] Is Ninja required to run this?

### ISSUE THREAD

**Issue by lcniel** [jamesdolezal/slideflow#384]
## Description
The various requirements specs note `ninja` as a requirement of this package, but I don't see `ninja` being necessary to execute it, since it only appears inside those specifications. Is `ninja` actually necessary to _run_ `slideflow`?

I would urge you to check all your requirements (since they are very extensive) along the same lines as it will help when building this package for HPC clusters.

**Comment by jamesdolezal** [comment]
The `ninja` requirement was inherited from the StyleGAN3 repository, a connection to which is used for our GAN functions. If you are not using the StyleGAN implementation in slideflow, it is not necessary.

We'll take an updated review of all requirements and trim back what we can. We've tried to segment off requirements into optional modules where possible (e.g., `pip install slideflow[torch]` will install pytorch-related requirements that aren't necessary for people using the Tensorflow backend). We can move ninja to a new `stylegan` extras.
