### ISSUE TITLE
[QUESTION] Is the Pandas < 2 restriction necessary?

### ISSUE THREAD

**Issue by lcniel** [jamesdolezal/slideflow#385]
In line with #384, I wonder if the requirement

```python
pandas<2
```

is really necessary, and/or whether it would be possible to update the package to support 2.0. The reason I ask is because it has been over one year since `pandas` 2.0 and separately building a very common library like `pandas` for this package consumes time and resources.

**Comment by jamesdolezal** [comment]
Thanks for the suggestion. At the time pandas 2.0 was released, there were breaking bugs that were causing issues. I'll work on testing support for 2.0 and updating our library accordingly.
