### ISSUE TITLE
unable to install slideflow 2.3.2

### ISSUE THREAD

**Issue by Meijian** [jamesdolezal/slideflow#403]
## Description

Hi @jamesdolezal, thanks for releasing 2.3.2 to fix some bugs. We tried to install it with pip but couldn't do it. It looks like the new version is not in PyPI database yet. Could you please help to check? Thanks!

## To Reproduce
1. pip install slideflow==2.3.2

**Comment by jamesdolezal** [comment]
Our testing pipeline caught an issue right before it went to PyPI, so I held back on uploading for a couple days until we could get it sorted out. You should be able to pull the update now.
